### PR TITLE
Create helper function to parse global options

### PR DESCRIPTION
**Pull request by grassias**

### CODE REVIEW

**Comment by grassias** [comment]
This PR aims to address issue #1947 after @alanshaw suggestions.

**Comment by hugomrdias** [comment]
i propose to do something like this 

```js

  let getIPFS = null
  cli
    .commandDir('commands')
    .middleware(argv => {
      getIPFS = argv.getIpfs = utils.singleton(cb => utils.getIPFS(argv, cb))
      return argv
    })
    .help()
    .strict()
    .completion()
  let exitCode = 0

  try {
    const { data } = await new YargsPromise(cli).parse(args)
    if (data) print(data)
  } catch (err) {
    debug(err)

    // the argument can have a different shape depending on where the error came from
    if (err.message || (err.error && err.error.message)) {
      print(err.message || err.error.message)
    } else {
      print('Unknown error, please re-run the command with DEBUG=ipfs:cli to see debug output')
    }

    exitCode = 1
  } finally {
    // If an IPFS instance was used in the handler then clean it up here
    if (getIPFS.instance) {
      try {
        const cleanup = getIPFS.rest[0]
        await cleanup()
      } catch (err) {
        debug(err)
        exitCode = 1
      }
    }
  }

  if (exitCode) {
    process.exit(exitCode)
  }
}
```

this way we use only one yargs instance

**Comment by grassias** [comment]
I'd like so but I'm not sure yet about how to handle it. Is there any test utility/method that exposes the instantiated IPFS object produced by cmds?

**Comment by hugomrdias** [comment]
to do this we need to change the way we test the cli check the example below

https://codesandbox.io/s/mqq66j9v6x

**Pull request merged**
