### PR TITLE
fix bitswap tests

### PR DESCRIPTION
**Pull request by diasdavid**
bitswap tests started failing for some reason (last time master had a merged they worked perfectly). Still figuring this one out.

The block is never exchanged

### CODE REVIEW

**Comment by diasdavid** [comment]
figured it out, it was a regression in js-ipfs-api. releasing and fixing :)

**Comment by diasdavid** [comment]
Gettting there, messages are being sent, but empty

 bitswap:network data from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +3ms
  bitswap:engine received empty message from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +0ms
  bitswap:network data from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +0ms
  bitswap:engine received empty message from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +0ms
  bitswap:network data from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +19ms
  bitswap:engine received empty message from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +1ms
  bitswap:network data from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +1ms
  bitswap:engine received empty message from QmTTLyjea7cKxFJd3TjYnKbvZBwqh1EQbhnrZ2482xsyVg +0ms

**Comment by diasdavid** [comment]
@dignifiedquire could help me with this one?

**Comment by dignifiedquire** [comment]
@diasdavid no need to fix anything in js-ipfs. The bug is in aegir, or rather in a nested dependency: https://github.com/dignifiedquire/aegir/issues/79#issuecomment-265995866

**Comment by dignifiedquire** [comment]
Should be fixed in aegir@9.2.1

**Pull request closed without merging**
