### PR TITLE
fix: add charset to script tag

### PR DESCRIPTION
**Pull request by achingbrain**
Maybe might fix the build?

### CODE REVIEW

**Comment by achingbrain** [comment]
\*shakes fist at bundlesize*

**Comment by achingbrain** [comment]
Seems to fix breakage caused by [this line](https://github.com/jkroso/parse-duration/blob/master/index.js#L14).  Though the breakage was introduced by a `libp2p-delegated-content-routing` upgrade which doesn't seem related but it does go away if you [downgrade](https://github.com/ipfs/js-ipfs/pull/2652) that dep.  But that's not a solution.  Only forward, eh? 🤷‍♂

**Comment by alanshaw** [comment]
urgh, that dep was added to the client in v40 which is now being used in the delegated routing module.

**Comment by achingbrain** [comment]
I noticed that, but this module has had [builds pass](https://github.com/ipfs/js-ipfs/runs/323381337) with the v40 rpc client which would have pulled that dep into the tree.  I guess it could it have been dead code elimination in the browser bundle or something?

**Comment by achingbrain** [comment]
A better fix: https://github.com/jkroso/parse-duration/pull/11

**Comment by alanshaw** [comment]
Unnecessary now :)

**Pull request closed without merging**
