### PR TITLE
refactor: convert libp2p config to async/await

### PR DESCRIPTION
**Pull request by jacobheun**
This updates libp2p configuration to the async refactor.

- [ ] Depends on [libp2p 0.27 release](https://github.com/libp2p/js-libp2p/issues/487)

### CODE REVIEW

**Comment by alanshaw** [comment]
@jacobheun prior art https://github.com/ipfs/js-ipfs/pull/2588

**Comment by jacobheun** [comment]
@alanshaw @lidel should we change and merge that PR into the `feat/ipfsx-boot-and-add` branch?

**Comment by alanshaw** [comment]
Ah, looking at the changes, I think we'll have to re-apply them to `feat/ipfsx-boot-and-add` when everything is merged in, will probably be a nightmare to merge.

**Comment by lidel** [comment]
@jacobheun  I closed #2588: it is small enough to apply it manually on this branch.
Its main purpose was to be a list of places to update `peerid` code, so we save time during the refactor.

**Comment by alanshaw** [comment]
@jacobheun I've pushed @lidel's changes from https://github.com/ipfs/js-ipfs/pull/2588 to https://github.com/ipfs/js-ipfs/pull/2683

**Comment by alanshaw** [comment]
@jacobheun FYI https://github.com/libp2p/js-libp2p-keychain/pull/40

**Comment by alanshaw** [comment]
@jacobheun over in https://github.com/ipfs/js-ipfs/pull/2683 I'm now blocked on some libp2p ❤️:

```console
➜ npx mocha test/core/interface.spec.js --bail

  interface-ipfs-core tests
    .add
      1) "before all" hook for "should add a File"
(node:78400) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
    at /Users/alan/Code/pl/ipfs/js-ipfs/node_modules/libp2p/src/index.js:114:52
    at Array.forEach (<anonymous>)
    at new Libp2p (node_modules/libp2p/src/index.js:113:29)
    at Object.libp2p (src/core/components/libp2p.js:28:14)
    at Proxy.start (src/core/components/start.js:37:38)
    at async InProc.start (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:125:7)
    at async Factory.spawn (node_modules/ipfsd-ctl/src/factory.js:141:7)
    at async Context.<anonymous> (node_modules/interface-ipfs-core/src/add.js:32:34)
(node:78400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jacobheun** [comment]
If we want to start gathering all of the refactor work into `refactor/async-await-roundup` this should be ready to look at. It's just configuration right now, but the other pieces will be harder to verify until we get a good baseline of tests running in #2683. I did cherry-pick these commits onto that branch and verified that `npx mocha test/core/interface.spec.js --bail` is getting passed libp2p setup. There may be some issues, but that might be easier to suss out after we have more tests running.

**Pull request closed without merging**
