### PR TITLE
fix(cli): make swarm addrs more resilient

### PR DESCRIPTION
**Pull request by jacobheun**
Dont fail if decapsulation of ipfs fails. Go node addresses typically wont contain their peerid

Fixes https://github.com/ipfs/js-ipfs/issues/1575

### CODE REVIEW

**Comment by alanshaw** [comment]
Nice! Please can we have a test?

**Comment by jacobheun** [comment]
@alanshaw sure, do you have a recommendation for testing the cli, it's been a while. I don't believe I can change addresses on the node via the api, so the options I can think of would be to add a go node to the test suite (this feels like it should go an interop though), or just mock and test the cli handler directly.

**Comment by alanshaw** [comment]
> just mock and test the cli handler directly.

This please 😁

**Comment by jacobheun** [comment]
I added a test for the cli handler. Since it's verifying process.stdout, the test cleanup isn't as clean as I'd like. If we just use the afterEach hook we'll lost the mocha output. We could stub the print function, but that would require a change to how it's being used in the cli file in order for the stub to work.

If we planned on adding more cli tests that just target the handlers directly (which would make cli tests much faster) we could build out some utilities to make the individual tests easier/cleaner to write.

**Comment by alanshaw** [comment]
@jacobheun if you change the handler to build up a string for the output and then return it it'll get [printed automatically](https://github.com/ipfs/js-ipfs/blob/master/src/cli/bin.js#L46). It might save you from having to stub `process.stdout` and allows you to more easily verify the output.

In the future we might want to think about passing `print` in via `argv` for easier testing.

**Comment by jacobheun** [comment]
>  if you change the handler to build up a string for the output and then return it it'll get printed automatically.

Ah, perfect! I updated the tests to check the returned output. I think testing the output returned from the handler is great. Then we only need to verify that bin is calling print appropriately.

Here is some truncated output running locally against an 0.36 rc daemon:
```log
$ node src/cli/bin.js swarm addrs
QmSoLnSGccFuZQJzRadHn95W2CrSFmZuTdDWP8HXaHca9z (11)
        /ip4/104.236.176.52/tcp/4001
        /ip6/2604:a880:1:20::1f9:9001/tcp/4001
        /ip6/::1/tcp/4001
        /ip6/2604:a880:1:20::1f9:9001/tcp/4001
        /ip6/fce3:c53b:c3c5:2f54:8bb0:b6d9:898e:f140/tcp/4001
        /ip4/127.0.0.1/tcp/8081/ws
        /ip4/127.0.0.1/tcp/4001
        /ip4/104.236.176.52/tcp/4001
        /ip4/10.12.0.8/tcp/4001
        /ip4/172.17.0.1/tcp/4001
        /p2p-circuit
QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ (4)
        /ip4/104.131.131.82/tcp/4001
        /p2p-circuit
        /ip4/127.0.0.1/tcp/4001
        /ip4/104.131.131.82/tcp/4001
```

**Comment by alanshaw** [comment]
Yeah it works for small non-streaming APIs, but print is still needed for commands like `ping`.

**Pull request merged**
