### PR TITLE
feat: adopt next aegir - part II

### PR DESCRIPTION
**Pull request by diasdavid**
squashed the first part into this new branch (the part I had "git merge" that was making things complicated for clean rebase)

### CODE REVIEW

**Comment by diasdavid** [comment]
I see this locally, although it doesn't stop the test:

```
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:195
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:196
      Error: Unhandled "error" event. (Error: Non-base58 character)
          at Stream.emit (events.js:185:19)
          at next (/Users/imp/code/js-ipfs/node_modules/pull-stream-to-stream/index.js:117:13)
          at /Users/imp/code/js-ipfs/node_modules/pull-stream/throughs/map.js:19:9
          at /Users/imp/code/js-ipfs/node_modules/pull-stream/sources/error.js:5:5
          at /Users/imp/code/js-ipfs/node_modules/pull-stream/throughs/map.js:11:7
          at Immediate.drain [as _onImmediate] (/Users/imp/code/js-ipfs/node_modules/pull-stream-to-stream/index.js:108:5)
          at runCallback (timers.js:781:20)
          at tryOnImmediate (timers.js:743:5)
          at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by diasdavid** [comment]
Also, seems like JEST skips CLI and HTTP-API tests

image

**Comment by dignifiedquire** [comment]
I made some progress in figuring out issues. 

-  Lint should be good now
- failing tests not canceling the test run is an issue on `master` as well, it turns out `api.inject` eats errors in the callback style, but it works fine when using the promise form, so I will change those
- not sure yet why some of http tests are failing yet, need to investigate some more

**Comment by dignifiedquire** [comment]
- not all tests are run because the setup is simply not right, the default checks for all `.spec.js` files and there are none for http or cli, so need to configure the require accordingly using the `node.js` file or something else

**Comment by dignifiedquire** [comment]
Another issue is that files that are entirely commented out, like https://github.com/ipfs/js-ipfs/blob/master/test/core/interface/dht.js throw an error in Jest

**Comment by diasdavid** [comment]
@dignifiedquire mind completing this PR?

**Comment by dignifiedquire** [comment]
I won't be able to look into this for the n.ext two weeks

**Comment by diasdavid** [comment]
@dryajov could you finish this PR?

**Comment by dryajov** [comment]
Yep, I got it. Also, I got the `feat/add-relay` working with the new aegir.

**Comment by dryajov** [comment]
Work to port to next aegir is already underway as part of this issue - #830.

**Comment by diasdavid** [comment]
Work happening here https://github.com/ipfs/js-ipfs/pull/830

@dryajov This works for now but let's keep the habit of having PR for different feature sets.

**Pull request closed without merging**
