### PR TITLE
feat: rev mfs and unixfs to support hamt in mfs

### PR DESCRIPTION
**Pull request by achingbrain**
In order to support really large directories

### CODE REVIEW

**Comment by alanshaw** [comment]
Would you mind rebasing for green CI please?

**Comment by achingbrain** [comment]
Yes, just adding some more tests to verify that adding nodes to sharded directories results in the same hashes as if they were added in one go by the importer.

**Comment by achingbrain** [comment]
@alanshaw this'll need ipfs/interface-ipfs-core#401 merging first.

**Comment by achingbrain** [comment]
Also https://github.com/ipfs/js-ipfs-http-client/pull/903

**Comment by alanshaw** [comment]
Both merged and released 🚢

**Comment by achingbrain** [comment]
Hmm, one test failure just now, pubsub related:

```
1) interface-ipfs-core tests,.name.pubsub.cancel

       should cancel a subscription correctly returning true:

     Error: Uncaught AssertionError: expected [ Array(1) ] to include '/ipns/QmcSaAyZTYcCq8M47jFsAabreuFzUNAPbVVjcYJZUWfczz' (webpack://ipfs/node_modules/chai/lib/chai/assertion.js:141 <- node_modules/aegir/src/config/karma-entry.js:36516)
```

**Comment by alanshaw** [comment]
Merging - browser test failure is unrelated - `.name.pubsub.cancel` - ping @vasco-santos

**Pull request merged**
