### PR TITLE
add ipld to validation config of options

### LINKED ISSUE #2031: TypeError: Expected a value of type `undefined` for `ipld` but received `{}`.
- **Version**: 0.35.0
- **Platform**: Darwin mac.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

#### Description: Error on trying to pass ipld option as described in documentation
```
TypeError: Expected a value of type `undefined` for `ipld` but received `{}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/src/superstruct.js:78:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:47:22)
      at Object.<anonymous> (components/storage/js-ipfs/index.ts:22:18)
      at step (components/storage/js-ipfs/index.ts:44:23)
      at Object.next (components/storage/js-ipfs/index.ts:25:53)

```

#### Steps to reproduce the error:
```
const IPFS = require('ipfs');
const node = new IPFS({
        ipld: { }
    });
```

### PR DESCRIPTION
**Pull request by Jonybang**
Fixes #2031

### CODE REVIEW

**Comment by alanshaw** [comment]
Thanks @Jonybang. We should add a quick test to ensure this is working!

**Comment by Jonybang** [comment]
I've fixed commit message, now CI should to pass

**Comment by Jonybang** [comment]
@alanshaw test like this?

**Comment by alanshaw** [comment]
I don't think `init` takes `ipld` as an option.

If you add a test in https://github.com/ipfs/js-ipfs/blob/master/test/core/create-node.spec.js instead that does a `new IPFS({ init: false, start: false, ipld: {} })` and checks that does not throw then we'd be all good!

**Comment by Jonybang** [comment]
@alanshaw now alright?

**Comment by alanshaw** [comment]
That'll do 👌. Thanks @Jonybang, I'll wait for CI 🍏 and then get this merged.

**Pull request merged**
