### PR TITLE
ci: enabling CI of sharness tests

### PR DESCRIPTION
**Pull request by AuHau**

### CODE REVIEW

**Comment by AuHau** [comment]
Related to #2561

**Comment by achingbrain** [comment]
Did this run in CI?  The output is:

```console
$ cd ./test/sharness && make
*** clean-test-results ***
rm -rf test-results
*** checking sharness ***
lib/install-sharness.sh
Cloning into 'sharness'...
Note: checking out 'ecba410b0b58400dd6517cfa6594fdac243d9056'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at ecba410 Merge pull request #54 from chriscool/readme-update
Sharness version ecba410b0b58400dd6517cfa6594fdac243d9056 is checked out!
mkdir -p ../bin
cd ../bin && ln -s ../../src/cli/bin.js ipfs
*** aggregate ***
ls test-results/t*-*.sh.*.counts | lib/sharness/aggregate-results.sh
ls: cannot access 'test-results/t*-*.sh.*.counts': No such file or directory
fixed   0
success 0
failed  0
broken  0
total   0
The command "cd ./test/sharness && make" exited with 0.
```

**Comment by AuHau** [comment]
@achingbrain sorry, it is still not ready. There is one test (GC stress test) that works locally but not on CI. I don't have cycles to debug it, I assume that there is some limitation of the sandbox where it runs, so I plan to skip it, but it does not work as expected in CI 😒

**Comment by AuHau** [comment]
@achingbrain alright so the skipping of GC test works correctly now, so I would say it is ready for review.

**Comment by AuHau** [comment]
Not sure why bundle-size complains as I have not added anything new...

**Comment by achingbrain** [comment]
> Not sure why bundle-size complains as I have not added anything new...

I think it's a transitive dependency update - it's fixed by https://github.com/ipfs/js-ipfs/pull/2571 so feel free to ignore it.

**Comment by alanshaw** [comment]
Lets close this in favour of getting the more extensive sharness working https://github.com/ipfs/js-ipfs/issues/2561#issuecomment-549275885

**Pull request closed without merging**
