### PR TITLE
fix: unsubscribe all topic for make is really stop

### PR DESCRIPTION
**Pull request by bluelovers**
if call pubsub subscribe
then after call stop, process will still running
so should remove it when stop

### CODE REVIEW

**Comment by achingbrain** [comment]
Thanks for opening this. Which process is still alive? The client or the daemon?

**Comment by bluelovers** [comment]
client

**Comment by achingbrain** [comment]
I'm trying to replicate this but I'm having problems. Here's my script that I run having previously started a daemon in the background:

```javascript
const client = require('ipfs-http-client')

const main = async () => {
  const ipfs = client('/ip4/127.0.0.1/tcp/5002/http')

  await ipfs.pubsub.subscribe('derp', () => {})
  await ipfs.stop()
}

main()
```

Against js-IPFS, this works as expected, the daemon shuts down and the client process exits.

Against go-IPFS, it works but it takes a long time, eventually the daemon prints

```
Error: 1 error occurred:
	* context deadline exceeded
```

and quits.

The way pubsub works over HTTP is that it opens a long-lived HTTP connection and receives events as newline-delimited JSON.  When the client unsubscribes it aborts that request which closes the connection

If the daemon is told to shut down and does not close those connections, that would keep the client process alive but it would also stop the daemon from quitting so would be a bug that needed to be fixed in core.

You haven't said if you're running against go-IPFS or js-IPFS.  If it's js-IPFS please can you provide a more complete example of how you're managing to trigger this behaviour?  If it's go-IPFS please open an issue on `ipfs/go-ipfs` about the slow shutdown time.

**Comment by bluelovers** [comment]
image

```ts
import ipfsClient from '@bluelovers/ipfs-http-client';

// auto detect go-ipfs and js-ipfs
ipfsClient()
	.then(async (ipfs) => {
		console.log(await ipfs.id())
		console.log(`subscribe`)
		await ipfs.pubsub.subscribe('xxxx', (msg)=> {
			console.log(msg)
		})

		console.log(`stop`)
		return ipfs.stop()
	})
	.finally(() => console.log(`should ending process`))
	.catch(err => console.trace(err))
;
```

```
yarn list v1.22.0
├─ @bluelovers/ipfs-http-client@1.0.42
├─ @lazy-ipfs/buffer-json@1.0.1
├─ @lazy-ipfs/detect-ipfs-companion@1.0.2
├─ fetch-ipfs@1.0.48
├─ fix-local-ipfs@1.0.32
├─ ipfs-api-check@1.0.41
├─ ipfs-api-type@1.0.1
├─ ipfs-bitswap@0.27.1
├─ ipfs-block-service@0.16.0
├─ ipfs-block@0.8.1
├─ ipfs-browser-util@1.0.2
├─ ipfs-core-utils@0.0.1
├─ ipfs-defaults@1.0.8
├─ ipfs-env@1.0.1
├─ ipfs-http-client@43.0.0
├─ ipfs-http-response@0.5.0
├─ ipfs-only-hash@2.0.1
├─ ipfs-repo-migrations@0.1.1
├─ ipfs-repo@1.0.1
├─ ipfs-server-list@1.0.27
├─ ipfs-types@1.0.19
├─ ipfs-unixfs-exporter@1.0.3
├─ ipfs-unixfs-importer@0.44.1
│  └─ ipfs-unixfs@0.3.0
├─ ipfs-unixfs@1.0.1
├─ ipfs-util-lib@1.0.27
├─ ipfs-utils@1.2.1
├─ ipfs-zip-stream@1.0.5
├─ ipfs@0.42.0
│  └─ ipfs-unixfs-importer@1.0.3
├─ ipfsd-ctl@3.0.0
│  └─ ipfs-utils@0.7.2
├─ ipld-in-memory@3.0.2
│  └─ ipfs-repo@0.30.1
├─ is-ipfs@0.6.3
├─ libp2p-delegated-content-routing@0.4.3
│  ├─ ipfs-http-client@42.0.0
│  └─ ipfs-utils@0.7.2
├─ libp2p-delegated-peer-routing@0.4.1
│  ├─ ipfs-http-client@42.0.0
│  └─ ipfs-utils@0.7.2
├─ poke-ipfs@1.0.16
├─ start-ipfs-daemon-lazy@1.0.3
├─ to-ipfs-hash@1.0.6
├─ to-ipfs-url@1.0.6
├─ use-ipfs-cli@1.0.42
└─ use-ipfs@1.0.49
Done in 1.24s.

```

**Comment by bluelovers** [comment]
process is stop

```
// auto detect go-ipfs and js-ipfs
ipfsClient()
	.then(async (ipfs) => {
		console.log(await ipfs.id())
		console.log(`subscribe`)
		await ipfs.pubsub.subscribe('xxxx', (msg)=> {
			console.log(msg)
		})

		await unsubscribeAll(ipfs)

		console.log(`stop`)
		return ipfs.stop()
	})
	.finally(() => console.log(`should ending process`))
	.catch(err => console.trace(err))
;
```

image

**Comment by bluelovers** [comment]
fix this in client is better

because some service is use go ifps too
even if  go-ipfs have new version
they maybe will not update it

---

infura.io
```
{
  version: '0.4.23',
  commit: '1f0de1aaf',
  repo: '7',
  system: 'amd64/linux',
  golang: 'go1.12.13'
}
```

and other is not free ipfs service

**Comment by achingbrain** [comment]
You appear to be using a fork of `ipfs-http-client` - can you please try with the non-forked version?

**Comment by bluelovers** [comment]
im sure it will 100% same as `ipfs-http-client`

because see this source code
https://github.com/bluelovers/ws-ipfs/blob/master/packages/ipfs-http-client/core.ts

**Comment by achingbrain** [comment]
Still, it'd be useful to eliminate extraneous code to figure out what's going on.

I can't replicate this problem locally in the way it is described, nor does it appear in any of our CI tests which spin up a node, subscribe to one or more pubsub channels then tear the whole thing down without first unsubscribing so we need to find out what's different between the setups.

**Comment by bluelovers** [comment]
```ts
import ipfsClient from '../index';
import { unsubscribeAll } from 'ipfs-util-lib/lib/ipfs/pubsub/unsubscribe';
import ipfsServerList from 'ipfs-server-list';
import ipfsClient2 from 'ipfs-http-client';

async function ipfsClient3(opts?)
{
	return ipfsClient2(opts ?? '/ip4/127.0.0.1/tcp/5001/http')
	return ipfsClient2(opts ?? '/ip4/127.0.0.1/tcp/5002/http')
}

// auto detect go-ipfs and js-ipfs
ipfsClient3(
	//ipfsServerList['infura.io'].API
)
	.then(async (ipfs) => {
		console.log(await ipfs.id().catch(e => null))
		console.log(await ipfs.version().catch(e => null))
		console.log(`subscribe`)
		await ipfs.pubsub.subscribe('xxxx', (msg)=> {
			console.log(msg)
		})

		//await unsubscribeAll(ipfs)

		console.log(`stop`)
		return ipfs.stop()
	})
	.finally(() => console.log(`should ending process`))
	.catch(err => console.trace(err))
;
```

image

**Comment by achingbrain** [comment]
How long are you letting this run for?  For me it takes just over 30 seconds to shut down the go-ipfs daemon vs under a second without the pubsub subscribe.

**Comment by bluelovers** [comment]
7 min after, node.js process still live, and i still didn't end it

**Comment by bluelovers** [comment]
30 min, node.js process still live

**Comment by bluelovers** [comment]
1hr 15min, it still live, i think is enough

**Comment by achingbrain** [comment]
I still can't see this happening. Do you have a repo somewhere with code I can run that shows the issue?

**Comment by bluelovers** [comment]
https://github.com/bluelovers/ws-ipfs

**Comment by achingbrain** [comment]
I mean, is there a test I can run that fails?

**Comment by bluelovers** [comment]
i test it in this repo

u just need copy code from https://github.com/ipfs/js-ipfs/pull/2969#issuecomment-609838004

**Comment by achingbrain** [comment]
I still can't replicate this.

1. Clone `https://github.com/bluelovers/ws-ipfs.git`
1. `npm install lerna`
1. `./node_modules/.bin/lerna bootstrap`
1. Created `test.js`:

```javascript
const ipfsClient2 = require('ipfs-http-client')

async function ipfsClient3(opts)
{
	return ipfsClient2('/ip4/127.0.0.1/tcp/5001/http')
}

// auto detect go-ipfs and js-ipfs
ipfsClient3(
	//ipfsServerList['infura.io'].API
)
	.then(async (ipfs) => {
		console.log(await ipfs.id().catch(e => null))
		console.log(await ipfs.version().catch(e => null))
		console.log(`subscribe`)
		await ipfs.pubsub.subscribe('xxxx', (msg)=> {
			console.log(msg)
		})

		//await unsubscribeAll(ipfs)

		console.log(`stop`)
		return ipfs.stop()
	})
	.finally(() => console.log(`should ending process`))
	.catch(err => console.trace(err))
```

Node output:

```console
$ node test.js 
{
  id: ...,
  publicKey: ...,
  addresses: [
    ...
  ],
  agentVersion: 'go-ipfs/0.4.23/',
  protocolVersion: 'ipfs/0.1.0'
}
{
  version: '0.4.23',
  commit: '',
  repo: '7',
  system: 'amd64/darwin',
  golang: 'go1.13.7'
}
subscribe
stop
should ending process
$ echo $?
0
```

Daemon output:

```console
$ /Applications/IPFS Desktop.app/Contents/Resources/app.asar.unpacked/node_modules/go-ipfs-dep/go-ipfs/ipfs daemon --enable-pubsub-experiment
Initializing daemon...
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/darwin
Golang version: go1.13.7
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/192.168.1.66/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/192.168.1.66/tcp/4001
Swarm announcing /ip4/86.164.228.231/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready

Error: 1 error occurred:
	* context deadline exceeded


Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
```

**Comment by achingbrain** [comment]
Can you write a test that fails without the patch in this PR please?  Otherwise I'm going to have to close this as I cannot replicate the problem you are reporting.

**Comment by achingbrain** [comment]
Closing as there's been no response.

**Pull request closed without merging**
