### PR TITLE
fix: add support for resolving to the middle of an IPLD block

### PR DESCRIPTION
**Pull request by Stebalien**
see: https://github.com/ipfs/interface-ipfs-core/pull/385

We'll have to wait for CI, I can't get the tests to run locally, even on master.

resolves https://github.com/ipfs/js-ipfs/issues/1763

### CODE REVIEW

**Comment by alanshaw** [comment]
resolves https://github.com/ipfs/js-ipfs/issues/1763

Thanks @Stebalien I'll pull this over the line as soon as I get a free moment.

Interested to know what your pain points were running the tests?

**Comment by Stebalien** [comment]
(ok, maybe I should have just read the error message: https://github.com/ipfs/js-ipfs/pull/1869)

**Comment by Stebalien** [comment]
It looks like something is going wrong with macos.

**Comment by alanshaw** [comment]
I've removed the test in `resolve.spec.js` as it's a duplicate of a test in `interface-ipfs-core`.

**Comment by alanshaw** [comment]
"EPERM: operation not permitted" error seen in the windows CI build will be resolved by https://github.com/ipfs/js-ipfs/pull/1889

**Pull request merged**
