### PR TITLE
fix: fail to open the webui page in the browser

### PR DESCRIPTION
**Pull request by LehaoLin**
I met the same issue as #2796, then I added this piece of code and the problem was solved.
Environment:
macOS 10.15.3
js-ipfs version: 0.4.2
System version: x64/darwin
Node.js version: 15.8.0

### CODE REVIEW

**Comment by achingbrain** [comment]
Thanks for opening this PR.  Most of this config is not used by js-IPFS so it's not relevant, it also opens up the HTTP API to any origin when running the HTTP API client in the browser so can't be merged as-is.

Which part do you think solved the problem?

**Comment by LehaoLin** [comment]
@achingbrain 
I think the `Mounts` part and the `Gateway` part mainly solved the problem, which are missed in the `.jsipfs/config`.
I can't open the webui without these two parts.
After I add them, I can open it successfully.

**Comment by achingbrain** [comment]
This can't be the case because `Mounts` a go-IPFS specific config key (it's not used by js-IPFS) and the `Gateway` key only affects the gateway, not the WebUI.  The headers you have added are related to CORS so should not stop you loading the page, though will loosen the security of any page you load through the gateway.

If you can add a test that fails against master and passes with this patch then that would help narrow the problem down but I don't think this can be merged as it stands as it's not clear how it solves the problem.

**Comment by lidel** [comment]
I believe CORS handling  of API port was refactored recently, I'm closing this as no longer relevant, cc @achingbrain to configm.

**Pull request closed without merging**
