### PR TITLE
refactor: enable DHT by default

### PR DESCRIPTION
**Pull request by alanshaw**
Note: also enables `randomWalk` and lowers connection manager limits in the browser.

Roadmap to getting DHT enabled by default in JS IPFS (TODO create issues/PRs for all of these):

* [x] Config changes (see [changes here](https://github.com/ipfs/js-ipfs/pull/1994/commits/7e242ece1642fb20efbfb5d5031baa6e73ef8555))
* [x] Daemon connection keepalive for long DHT requests (will arrive with the switch to using the fetch API in the http client which adds timeout option)
* [ ] [DHT reprovide](https://github.com/ipfs/js-ipfs/pull/2184)
* [ ] [Connection prioritisaton](https://github.com/libp2p/js-libp2p/issues/369) (do not prune preload nodes)
* Bug fixes:
    * [x] https://github.com/ipfs/js-ipfs-bitswap/pull/194
    * [x] https://github.com/libp2p/js-libp2p-kad-dht/pull/127
* Testing:
    * [x] DHT interface tests https://github.com/ipfs/interface-js-ipfs-core/pull/486
    * [ ] Merge interop tests https://github.com/ipfs/interop/pull/36
    * [ ] Create [DHT integration](https://github.com/ipfs/js-ipfs/issues/2093#issuecomment-495238655) tests
    * [ ] Manual DHT testing call

### CODE REVIEW

**Comment by pgte** [comment]
Let me give you a hand on this

**Comment by joeykrug** [comment]
What’s eta on this getting merged

**Comment by alanshaw** [comment]
@joeykrug we're aiming to get this merged and released before [IPFS Camp](https://camp.ipfs.io/).

**Comment by jacobheun** [comment]
I've pushed up the config changes here and updated the PR comment to include an updated link to the commit of the changes.

**Comment by daviddias** [comment]
Hi! js-ipfs master just got a whole new set of automated tests with #2528, https://github.com/ipfs/js-ipfs/pull/2440 and also running some of the test suites from our early testers (hi5 to  @achingbrain for setting it all up!). **Would you mind rebasing the master branch on this PR to ensure it runs all the latest tests? Thank you!**

**Comment by daviddias** [comment]
@alanshaw what is the latest state on DHT in JS land? PS: Shouldn't this be labeled as P0?

**Comment by alanshaw** [comment]
@daviddias the checklist at the top is up to date. I've labelled it p0.

**Comment by achingbrain** [comment]
Fixed by #3947

**Pull request closed without merging**
