### PR TITLE
fix: remove unused var

### PR DESCRIPTION
**Pull request by fsdiogo**
Removed an unused var that was producing a linter error.

### CODE REVIEW

**Comment by JonKrone** [comment]
Thanks @fsdiogo!

@VictorBjelkholm Looking at #1230, and then looking at a couple other PRs, it seems like linting isn't being run during CI anymore. Is this a regression, intentional, or am I missing something?

**Comment by diasdavid** [comment]
It should be run in Circle. Can you add it back it too? Thanks @fsdiogo :)

**Comment by JonKrone** [comment]
update from IRC: @VictorBjelkholm is working on adding it to jenkins 👍

**Comment by VictorBjelkholm** [comment]
I've added linting to the jenkins job now and retried the jenkins jobs for this pr.

**Pull request merged**
