### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by crypt0maniak**

### CODE REVIEW

**Comment by achingbrain** [comment]
The engines field is only advisory so it'll just print a warning out if you're not running node 12, and the package.json you've added the field to is not published to npm so no-one's installing it.

Does this solve a problem you are having?

**Comment by crypt0maniak** [comment]
Yeah, I actually meant to push this to another branch of a forked version, but accidently pushed it here :/

But I got a question related to js-ipfs in webbrowsers. Are there any docs and/or examples on how to implement and use it correctly with and without using ws/wss connections?

**Comment by achingbrain** [comment]
Have you looked at the [examples](https://github.com/ipfs/js-ipfs/tree/master/examples)?  The [browser-exchange-files](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-exchange-files) example shows you how to use WebRTC for browser-to-browser communication.

**Comment by crypt0maniak** [comment]
> Have you looked at the [examples](https://github.com/ipfs/js-ipfs/tree/master/examples)? The [browser-exchange-files](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-exchange-files) example shows you how to use WebRTC for browser-to-browser communication.

Thanks. The [browser-exchange-files](https://github.com/ipfs/js-ipfs/tree/master/examples/browser-exchange-files) is almost exactly what I need.

**Pull request closed without merging**
