### PR TITLE
feat(factory): add ipfs factory, verify it works with object tests

### PR DESCRIPTION
**Pull request by diasdavid**
- [x] create ipfsFactory
- [x] test it
- [x] make all interface-ipfs-core tests use ipfsFactory

### CODE REVIEW

**Comment by diasdavid** [comment]
Up for CR

**Comment by dignifiedquire** [comment]
Do we still need the rest of things in `test/util`?

**Comment by diasdavid** [comment]
@dignifiedquire we still need for now. I want to phase them out and use just IPFS factory.

**Comment by dignifiedquire** [comment]
okay, lgtm if ci is happy

**Comment by diasdavid** [comment]
thank you :)

**Pull request merged**
