### PR TITLE
Fix the welcome message and throw error when trying to cat a non-exis…

### LINKED ISSUE #1031: Facing an issue with cat-ing the files
- **Version**: js-ipfs version: 0.26.0
- **Platform**: Darwin Arpits-MBP.Dlink 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
- **Subsystem**: CLI

#### Steps to reproduce the error:
```
➜  jsipfs init

initializing ipfs node at /Users/arpit/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmboTK9e8rMroKwEooEn5KRorUu4k2RHjqk9MH4JDNzbvw
to get started, enter:

	 jsipfs files cat /ipfs/QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB

➜  jsipfs files cat /ipfs/QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB

Hello and Welcome to IPFS!

██╗██████╗ ███████╗███████╗
██║██╔══██╗██╔════╝██╔════╝
██║██████╔╝█████╗  ███████╗
██║██╔═══╝ ██╔══╝  ╚════██║
██║██║     ██║     ███████║
╚═╝╚═╝     ╚═╝     ╚══════╝

If you're seeing this, you have successfully installed
IPFS and are now interfacing with the ipfs merkledag!

 -------------------------------------------------------
| Warning:                                              |
|   This is alpha software. Use at your own discretion! |
|   Much is missing or lacking polish. There are bugs.  |
|   Not yet secure. Read the security notes for more.   |
 -------------------------------------------------------

Check out some of the other files in this directory:

  ./about
  ./help
  ./quick-start     <-- usage examples
  ./readme          <-- this file
  ./security-notes
➜  jsipfs files cat /ipfs/QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB/security-notes
/usr/local/lib/node_modules/ipfs/src/core/components/files.js:92
          callback(null, toStream.source(files[files.length - 1].content))
                                                                ^

TypeError: Cannot read property 'content' of undefined
    at pull.collect (/usr/local/lib/node_modules/ipfs/src/core/components/files.js:92:65)
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/sinks/reduce.js:10:5
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/sinks/drain.js:20:24
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/flatten.js:35:20
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/map.js:19:9
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/map.js:19:9
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/sources/values.js:19:7
    at read (/usr/local/lib/node_modules/ipfs/node_modules/pull-defer/source.js:14:10)
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/map.js:11:7
    at /usr/local/lib/node_modules/ipfs/node_modules/pull-stream/throughs/map.js:11:7
```
Am I doing something wrong?

### PR DESCRIPTION
**Pull request by atvanguard**
…tent file [Fixes #1031]

### CODE REVIEW

**Comment by dryajov** [comment]
@atvanguard can you please add some tests verifying this works.

**Comment by atvanguard** [comment]
@dryajov Added. Let me know if something needs to be improved.

**Comment by diasdavid** [comment]
@atvanguard Looking good. Mind checking my comment? Otherwise, LGTM

**Comment by atvanguard** [comment]
@diasdavid Incorporated the changes and increased the timeout for a test that was failing.

**Pull request merged**
