### PR TITLE
feat: web ui latest

### PR DESCRIPTION
**Pull request by hacdias**
Relevant release notes can be found on [v2.5.5](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.5).

### CODE REVIEW

**Comment by achingbrain** [comment]
Do you think this could be an IPNS name instead of a CID?  That way you wouldn't have to keep submitting these PRs that just change the hash.

**Comment by hacdias** [comment]
The latest released/stable is always on `/ipns/webui.ipfs.io` and the latest commit to master on `/ipns/dev.webui.ipfs.io` so I guess we can change it to the former.

**Comment by achingbrain** [comment]
Feature freeze was on Monday.  This missed the deadline and will go out in the next release.

**Comment by achingbrain** [comment]
Hmm, actually having just seen https://github.com/ipfs/js-ipfs/pull/2281 and the discussion on https://github.com/ipfs/go-ipfs/pull/6530 maybe we should switch back to the `CID` before release.

**Pull request merged**
