### PR TITLE
feat: update all dependencies

### PR DESCRIPTION
**Pull request by dignifiedquire**

### CODE REVIEW

**Comment by diasdavid** [comment]
Seems that there is console.log from somewhere

image

And .add is (or continues) unstable

image

**Comment by diasdavid** [comment]
+ merge conflicts. Could you rebase @dignifiedquire ?

**Comment by dignifiedquire** [comment]
@diasdavid rebased, those issues are not coming from this branch

**Comment by diasdavid** [comment]
👍

**Pull request merged**
