### PR TITLE
dht.provide() should accept string keys (#2573)

### PR DESCRIPTION
**Pull request by reasv**
Solving https://github.com/ipfs/js-ipfs/issues/2573
ipfs.dht.provide() now accepts strings as well as CID objects, and attempts to convert them to the latter.

### CODE REVIEW

**Comment by reasv** [comment]
Failed because of a linting issue

**Comment by reasv** [comment]
Pushed a fix

**Comment by reasv** [comment]
I'll do it

**Comment by reasv** [comment]
https://github.com/ipfs/interface-js-ipfs-core/pull/555

**Comment by alanshaw** [comment]
Thanks @reasv 🥰

**Pull request merged**
