### PR TITLE
feat: allow `--debug`

### PR DESCRIPTION
**Pull request by bluelovers**
https://github.com/visionmedia/debug#set-dynamically

### CODE REVIEW

**Comment by achingbrain** [comment]
There is no need for this, you can just do:

```console
$ DEBUG=ipfs* jsipfs add ./somefile.txt
```

**Comment by bluelovers** [comment]
i think use `--debug` is more easy

why **only** allow user debug when set env var?

**Comment by achingbrain** [comment]
`--debug` only sets `DEBUG=ipfs:cli` which doesn't help with diagnosing problems with libp2p or other system components.

The nice thing about `DEBUG=ipfs*` is it presents a uniform way of getting debug logs out of IPFS in the browser, on the CLI, within your app, etc - I don't think adding special-case code to the CLI is the way forward.

**Comment by bluelovers** [comment]
@achingbrain  it just need update code for keep it
https://github.com/ipfs/js-ipfs/pull/2967

**Pull request closed without merging**
