### PR TITLE
chore: update ipfs-repo

### PR DESCRIPTION
**Pull request by hugomrdias**
update ipfs-repo but still pinned to be safe

### CODE REVIEW

**Comment by alanshaw** [comment]
> still pinned to be safe

Not sure I understand why? It was pinned because 0.25.1 was breaking builds if this is resolved we can unpin right?

**Comment by hugomrdias** [comment]
Mainly to force a PR if we need to make more tweaks, as this issue doesn't happen always. In the first change we didn't do a PR and we only found the problem already in master.

**Comment by alanshaw** [comment]
Would you mind rebasing for green CI please?

**Comment by hugomrdias** [comment]
ci green

**Pull request merged**
