### PR TITLE
New preload nodes

### PR DESCRIPTION
**Pull request by thattommyhall**

### CODE REVIEW

**Comment by achingbrain** [comment]
Is there any testing that needs to be done on these nodes or is this good to go?  Just thinking of the previous PR that got [pulled](https://github.com/ipfs/js-ipfs/pull/3020#issuecomment-623915620).

**Comment by thattommyhall** [comment]
I'd still like to write a little script that uses each as a preload and add it into our monitoring, you can hold off merge till I've done that if you like. 
The 2 existing ones are getting warm is why I got this up before that

**Comment by alanshaw** [comment]
I ran the tests here https://github.com/alanshaw/js-ipfs-preload-tester and they are working as expected:

```console
$ npm start -- --api-addr=/dns4/node2.preload.ipfs.io/https --bootstrap-addr=/dns4/node2.preload.ipfs.io/tcp/443/wss/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS

> js-ipfs-preload-tester@0.0.0 start /Users/alan/Code/pl/ipfs/js-ipfs-preload-tester
> node bin "--api-addr=/dns4/node2.preload.ipfs.io/https" "--bootstrap-addr=/dns4/node2.preload.ipfs.io/tcp/443/wss/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS"

🌎 Using preloader API Address: /dns4/node2.preload.ipfs.io/https
🥾 Using preloader Bootstrap Address: /dns4/node2.preload.ipfs.io/tcp/443/wss/p2p/QmV7gnbW5VTcJ3oyM2Xk1rdFBJ3kTkvxc87UFGsun29STS
💾 Data that will be used in the test: "Test content created on Wed May 06 2020 11:30:43 GMT+0100 (British Summer Time)"
🏃‍♀️ Running the test...
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/192.168.0.3/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/169.254.210.54/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Test execution time: 7897.077ms
🥳 This preloader is working as expected
```

```console
$ npm start -- --api-addr=/dns4/node3.preload.ipfs.io/https --bootstrap-addr=/dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN

> js-ipfs-preload-tester@0.0.0 start /Users/alan/Code/pl/ipfs/js-ipfs-preload-tester
> node bin "--api-addr=/dns4/node3.preload.ipfs.io/https" "--bootstrap-addr=/dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN"

🌎 Using preloader API Address: /dns4/node3.preload.ipfs.io/https
🥾 Using preloader Bootstrap Address: /dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN
💾 Data that will be used in the test: "Test content created on Wed May 06 2020 11:31:38 GMT+0100 (British Summer Time)"
🏃‍♀️ Running the test...
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/192.168.0.3/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/169.254.210.54/tcp/4002/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmXESqr1Tnedo3XpKzsEVxpXvFU26ChGqJXw7k42CKABdd
Test execution time: 3128.328ms
🥳 This preloader is working as expected
```

**Comment by thattommyhall** [comment]
Legends both, thanks

**Pull request merged**
