### PR TITLE
feat(files.add): update API to conform latest interface-ipfs-core updates

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by dignifiedquire** [comment]
CI is pretty unhappy

**Comment by dignifiedquire** [comment]
code itself lgtm

**Comment by diasdavid** [comment]
It will get happy after https://github.com/ipfs/interface-ipfs-core/pull/56 is merged and released

**Comment by noffle** [comment]
:horse: LGTM

**Pull request merged**
