### PR TITLE
[WIP] Improve Transfer Files Example

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Comment by diasdavid** [comment]
Screeenshot :D

**Comment by hacdias** [comment]
Haven't changed the design very much. Just simplified the CSS and JS. Any suggestions? I think we should be able to toggle the peers.

image

image

**Comment by hacdias** [comment]
Just tweaked the header

image

**Comment by diasdavid** [comment]
@hacdias here you go:

image

**Comment by hacdias** [comment]
Nice!! Will do that tomorrow probably :)

**Comment by hacdias** [comment]
@diasdavid look at this 😄

**Comment by hacdias** [comment]
getting this error:

image

When using IPFS from `//unpkg.com/ipfs/dist/index.min.js`

**Comment by diasdavid** [comment]
@hacdias see https://github.com/ipfs/js-ipfs/issues/1131. Wanna take the lead at fixing the issue in the aegir's Webpack config?

**Comment by diasdavid** [comment]
Awesome work @hacdias, almost there!

Here is some more feedback :)

image

**Comment by diasdavid** [comment]
Also, I liked this variation:

image

Perhaps do `IPFS | InterPlanetary File Exchange`

**Comment by hacdias** [comment]
localhost_12345_

**Comment by hacdias** [comment]
localhost_2015_

I think it's done for now 😄 What do you think @diasdavid ?

**Comment by diasdavid** [comment]
@hacdias Looking good! One last small request. Can you make a better use of the screen size? In my 15" it looks like:

image

It is a shame to be breaking lines when the columns could just be wider

**Comment by diasdavid** [comment]
🐞 Ah, just noticed that there is no way to download the files anymore.

**Comment by hacdias** [comment]
Check it now please 😄

**Comment by diasdavid** [comment]
Wooot! it is working now. Thank you @hacdias :D

**Comment by hacdias** [comment]
😀😃😅

**Pull request merged**
