### PR TITLE
[WIP] feat: Add rendezvous

### PR DESCRIPTION
**Pull request by mkg20001**
Adds support for [libp2p-rendezvous](https://github.com/libp2p/js-libp2p-rendezvous) protocol

ToDOs:
 - [ ] Make this less hacky
 - [ ] Hide it behind a flag for now?

### CODE REVIEW

**Comment by pgte** [comment]
@mkg20001 @alanshaw Any news on this? We need this for https://github.com/ipfs-shipyard/peer-star-app/issues/5

**Comment by alanshaw** [comment]
@pgte in lieu of it being a default discovery module can you pass it to `libp2p.peerDiscovery` temporarily in `peer-star-app`?

**Comment by mkg20001** [comment]
@pgte This would have to be properly integrated into libp2p instead of IPFS, I think. Current blocker is that rendezvous requires swarm, and swarm should depend on rendezvous as a discovery module. (chicken&egg problem). There needs to be a better solution to that than just adding more hacks.

**Comment by alanshaw** [comment]
@mkg20001 shall we close this PR for the time being?

**Comment by mkg20001** [comment]
@alanshaw Yes. I think the whole "X requires swarm but is component for swarm" situation requires a refactor anyways

**Pull request closed without merging**
