### PR TITLE
fix(files.add): handle weird directory names

### PR DESCRIPTION
**Pull request by richardschneider**
`glob` was interpreting the '[' in `wierd [v0]` as a special magic character.  According to its documentation, a caller should be able to escape it with `\`; but it does not work.

See the [glob issue](https://github.com/isaacs/node-glob/issues/277).

### CODE REVIEW

**Comment by richardschneider** [comment]
@diasdavid Both travis and circle are queuing the build!  Hopefully, they will get built by the time you get around to this.

**Comment by richardschneider** [comment]
@diasdavid it looks like some wrong code has entered `js-ipfs`.  Here's some errors from my last build on Circle CI

```
1) HTTP API
       ## interface-ipfs-core over ipfs-api
         .files
           .cat
             errors on unknown path:
     AssertionError: expected 'd.end is not a function' to be one of [ Array(2) ]
      at ipfs.files.cat.catch (node_modules/interface-ipfs-core/src/files.js:439:36)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

  2) interface-ipfs-core tests
       .files
         .cat
           errors on unknown path:
     Uncaught TypeError: d.end is not a function
      at pull.collect (src/core/components/files.js:140:20)
      at node_modules/pull-stream/sinks/reduce.js:10:5
      at node_modules/pull-stream/sinks/drain.js:20:24
      at node_modules/pull-stream/throughs/map.js:19:9
      at node_modules/pull-stream/throughs/filter.js:17:11
      at node_modules/pull-stream/throughs/filter.js:17:11
      at node_modules/pull-stream/throughs/filter.js:17:11
      at node_modules/pull-stream/throughs/flatten.js:35:20
      at drain (node_modules/pull-paramap/index.js:23:11)
      at node_modules/pull-paramap/index.js:63:9
      at nextStream (node_modules/pull-stream/throughs/flatten.js:33:9)
      at node_modules/pull-stream/throughs/flatten.js:21:29
      at node_modules/pull-stream/sources/empty.js:5:5
      at nextChunk (node_modules/pull-stream/throughs/flatten.js:20:9)
      at node_modules/pull-stream/throughs/flatten.js:41:11
      at drain (node_modules/pull-paramap/index.js:19:11)
      at node_modules/pull-paramap/index.js:45:13
      at dag.get (node_modules/ipfs-unixfs-engine/src/exporter/resolve.js:42:9)
      at _get (node_modules/ipld-resolver/src/index.js:133:9)
      at node_modules/async/internal/once.js:12:16
      at next (node_modules/async/waterfall.js:21:29)
      at node_modules/async/internal/onlyOnce.js:12:16
      at r.util.deserialize (node_modules/ipld-resolver/src/index.js:371:13)
      at multihashing (node_modules/ipld-dag-pb/src/dag-node/create.js:61:7)
      at Multihashing.Multihashing.digest (node_modules/multihashing-async/src/index.js:33:5)
      at setImmediate (node_modules/multihashing-async/src/utils.js:8:7)
      at Immediate.<anonymous> (node_modules/async/internal/setImmediate.js:27:16)

  3) interface-ipfs-core tests
       .pubsub
         single node
           .subscribe
             to one topic with Promise:
     Uncaught TypeError: callback is not a function
      at setImmediate (src/core/components/pubsub.js:27:28)
      at Immediate.<anonymous> (node_modules/async/internal/setImmediate.js:27:16)

  4) interface-ipfs-core tests
       .pubsub
         single node
           .subscribe
             to one topic with options and Promise:
     Uncaught TypeError: callback is not a function
      at setImmediate (src/core/components/pubsub.js:27:28)
      at Immediate.<anonymous>
```

**Comment by diasdavid** [comment]
@richardschneider can you rebase master onto this branch?

**Comment by richardschneider** [comment]
I've never `rebased`, I only do merge.  Can you give me the instructions.

**Comment by diasdavid** [comment]
@richardschneider There are some really good tutorials out there that will give you a full understanding of what rebase means:

- https://git-scm.com/docs/git-rebase
- https://www.git-scm.com/book/en/v2/Git-Branching-Rebasing
- https://www.youtube.com/watch?v=dO9BtPDIHJ8

Let me know if this works for you, otherwise, I can do it for now and you can practice in another repo. You will use it more times in the future.

**Comment by richardschneider** [comment]
I've broken this with the rebase.  Will open another PR.

**Pull request closed without merging**
