### PR TITLE
docs(example): explore eth through IPFS

### PR DESCRIPTION
**Pull request by diasdavid**
Fun :)

image

image

### CODE REVIEW

**Comment by diasdavid** [comment]
@kumavis we need a pretty print for this stuff :) but yeah, it works \o/ woot! :D

**Comment by kumavis** [comment]
@diasdavid this helps with pretty print and generating cids https://github.com/kumavis/eth-ipld
I'll clean it up and publish

**Comment by kumavis** [comment]
@diasdavid can we use the normal ipfs explorer to explore ethereum links?

**Comment by diasdavid** [comment]
Which is the 'normal' ipfs explorer? graphmd?

**Comment by kumavis** [comment]
go-ipfs webui

**Pull request merged**
