### PR TITLE
feat: support --raw-leaves and --cid-base

### PR DESCRIPTION
**Pull request by achingbrain**
Updates to the latest version of `js-ipfs-mfs` to properly support the `--raw-leaves` argument and allow formatting CIDs in base32 when doing `ls` and `stat` mfs operations.

### CODE REVIEW

**Comment by achingbrain** [comment]
Documented in ipfs/interface-ipfs-core#334

**Comment by alanshaw** [comment]
@achingbrain I think these out of date tests are causing the failures:

https://github.com/ipfs/js-ipfs/blob/f4344b0e397639df6f26d904be9a015b763e4338/test/cli/files.js#L208-L258

**Comment by achingbrain** [comment]
CI is full of yarn/npm fail:

```
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:98:30)
    at /tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:23451:28)
    at Function.<anonymous> (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/tmp/jenkins/workspace/IPFS_js-ipfs_PR-1454-LVUG5VEDDMITOKZKGN2KSE7SOUUVN4UCYDGEUJ27TDHOH7PM53CQ/node_modules/yarn/lib/cli.js:52217:19)

script returned exit code 1
```

But you are right they should fail.  For me locally they pass because an error is returned while executing the command, but the error is not the one expected and the tests don't assert anything past 'there should be an error' so they pass where they should fail.

I've updated them to expect success and not failure conditions.

**Comment by parkan** [comment]
seeing green CI, can we get this merged and we'll improve coverage after the summit?

**Pull request merged**
