### PR TITLE
feat: replace websocket-star with stardust

### PR DESCRIPTION
**Pull request by mkg20001**

### CODE REVIEW

**Comment by mkg20001** [comment]
@alanshaw So this one would be finished. Sorry for the confusion in case you've already started a PR

**Comment by alanshaw** [comment]
Blocked by https://github.com/libp2p/js-libp2p-stardust/pull/14

**Comment by talentlessguy** [comment]
https://github.com/libp2p/js-libp2p-stardust/pull/14 seems to have been merged but it's archived

**Comment by achingbrain** [comment]
Stardust never happened, the WebRTC transport will be this one: https://github.com/little-bear-labs/js-libp2p-webrtc

**Pull request closed without merging**
