### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by vmx**

### CODE REVIEW

**Comment by diasdavid** [comment]
Done on master with attention to @alanshaw CR

**Comment by vmx** [comment]
@diasdavid I don't see it on master. When I checkout master and do an `ncu` I still see a lot of non updated packages.

**Comment by diasdavid** [comment]
Just ran ncu right now

```
» ncu
Using /Users/imp/code/js-ipfs/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠴ :
 hapi  ^16.6.2  →  ^17.6.0
 joi   ^13.4.0  →  ^14.0.2
```

**Comment by vmx** [comment]
Sorry for the noise, you're right, I forgot the to pull.

**Pull request closed without merging**
