### PR TITLE
yarn.lock

### PR DESCRIPTION
**Pull request by dignifiedquire**
For those who want it, making installs a lot faster.

### CODE REVIEW

**Comment by dignifiedquire** [comment]
CI breaks because of: https://github.com/ipfs/js-ipfs/issues/781

**Comment by VictorBjelkholm** [comment]
@dignifiedquire is https://github.com/ipfs/js-ipfs/issues/781 blocking this from getting merged? Should not be compatible no matter if we have a yarn.lock or not.

**Comment by dignifiedquire** [comment]
@VictorBjelkholm #781 blocks this because ci breaks in this PR because of it

**Comment by diasdavid** [comment]
Going to close as it is already out of date. We will chat about yarn next week :)

**Pull request closed without merging**
