### PR TITLE
feat: jsipfs add --only-hash

### PR DESCRIPTION
**Pull request by JonKrone**
This enables generating a would-be hash for content via http or cli: `jsips add --only-hash <file>`, `ipfs.add(<content>, { onlyHash: true })`

image

Turns out unix-fs-engine has been ready for this since https://github.com/ipfs/js-ipfs-unixfs-engine/pull/183.

### Depends on:
- [ ] https://github.com/ipfs/js-ipfs-api/pull/700

### Related issues:
https://github.com/ipfs/js-ipfs-api/issues/509
https://github.com/ipfs/js-ipfs/issues/1205

### CODE REVIEW

**Comment by diasdavid** [comment]
This PR needs ipfs/js-ipfs-api#700 to be released. Meanwhile, @JonKrone can you fix the merge conflicts?

**Comment by diasdavid** [comment]
This PR needs ipfs/js-ipfs-api#700 to be released. Meanwhile, @JonKrone can you fix the merge conflicts?

**Comment by JonKrone** [comment]
Great. While waiting for ipfs/js-ipfs-api#700 to be in a release, I am working on https://github.com/ipfs/js-ipfsd-ctl/pull/212

**Comment by JonKrone** [comment]
Update: This is ready as soon as the next release of ipfs-api is out :). Just needs a code review and CI rerun after that.

**Comment by diasdavid** [comment]
Merging into the branch so that I can then update the deps.

**Pull request merged**
