### PR TITLE
fix: cat: test file existence after filtering

### LINKED ISSUE #1142: jsipfs cat on a directory not working correctly
- **Version**: 0.27.3
- **Platform**: macOS 10.13.1
- **Subsystem**: files

#### Type:
Bug

#### Severity:
High

#### Description:
`ipfs cat` on a directory displays the contents of a file in a sub directory, not the error "this dag node is a directory"

#### Steps to reproduce the error:

```sh
$ jsipfs init
initializing ipfs node at /Users/alan/.jsipfs
generating 2048-bit RSA keypair...done
peer identity: QmU8eJXWVYudzSrV5fxQuptmK1haqMG6E1eKP47xuF4e1K
to get started, enter:

	 jsipfs files cat /ipfs/QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/readme
```
lets cat that directory:
```sh
$ jsipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
Wait, I was expecting some sort of directory error...
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr
Error: this dag node is a directory
```
...yeah like that
```sh
$ ipfs cat QmfGBRT6BbWJd7yUc2uYdaUZJBbnEFvTqehPFoSMQ6wgdr/tour/0.0-intro
WIP

# 0.0 - Introduction

Welcome to IPFS! This tour will guide you through a few of the
features of this tool, and the most common commands. Then, it will
immerse you into the world of merkledags and the amazing things
you can do with them.

...
```
weirdness, it is displaying a file in a sub folder...

### PR DESCRIPTION
**Pull request by pgte**
Should fix #1142

### CODE REVIEW

**Comment by diasdavid** [comment]
@alanshaw can you test with this PR?

**Comment by alanshaw** [comment]
screen shot 2017-12-14 at 22 12 25

I'm getting "No such file" error now

**Comment by diasdavid** [comment]
.cat is returning two files for a directory?

**Comment by pgte** [comment]
@diasdavid the exporter is exporting the dir, and apparently cat is using that export stream, so it has to filter based on path.

The problem I see here is that the `ipfsPath` that is being passed in has the `/ipfs/` trailer, which I guess was supposed to have been removed before being passed in.

@alanshaw could you tell me the API call are you doing to trigger this cat?

**Comment by alanshaw** [comment]
It's a direct call to js-ipfs in the browser - `ipfs.files.cat`.

**Comment by alanshaw** [comment]
Example https://github.com/alanshaw/ipfs.files.cat-bug

**Comment by pgte** [comment]
@alanshaw thanks for the test!
Looks like the latest abbaebd6e5fa7b6ee95b84f74c80c3f1c4fd72ca fixes this:

web_inspector_ _localhost

**Comment by alanshaw** [comment]
Directories now display so \o/

I'm so sorry @pgte but this change _may_ have caused an issue elsewhere...listings for nested directories (using `ipfs.ls`) are now not correct:

Expected (using go-ipfs):

screen shot 2017-12-15 at 12 13 10

Actual (using js-ipfs):

screen shot 2017-12-15 at 12 13 21

I'll check now if this was an existing bug or not and report back.

**Comment by diasdavid** [comment]
@alanshaw I believe that is another bug , see https://github.com/ipfs/js-ipfs/issues/1079

**Pull request merged**
