### PR TITLE
test: remove unnecessary api tests

### PR DESCRIPTION
**Pull request by jacobheun**
The http-api test suite is doing redundant work. The removed tests were spinning up a daemon to run the http-api tests by proxy. This duplicates the code paths the cli tests are already using. Also, the inject http-api tests test the api directly, without spinning up a daemon. This is a better, more performant approach and makes these deleted tests redundant.

The risk of exposing future code stability issues due to removing these tests is extremely low since, as mentioned above, the api is being tests twice: in isolation and via the cli.

## Test Time Savings

The following table shows a cost savings in testing time as shown on jenkins between one of the latest master builds and this branch. While this comparison is isolated to a single build of each branch, the build times for other builds of the respective branches are not significantly different and the magnitude of the change warrants this PR.

|  | Mac 8.x | Mac 10.x | Linux 8.x | Linux 10.x | Win 8.x | Win 10.x | Coverage |
|--- |--- |--- |--- |--- |--- |--- |--- |
|[master 22](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/master/22/pipeline)| 29m 3s | 27m 38s | 22m 54s | 21m 48s | 28m 4s | 28m 8s | 27m 30s |
|[api-cleanup 2](https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs/detail/test%2Fapi-cleanup/2/pipeline/)| 15m 37s | 15m 15s | 14m 0s | 13m 0s | 16m 16s | 16m 46s | 16m 5s |
|Time reduction* | -46% | -45% | -39% | -40% | -42% | -40% | -41% |

\* Time reduction percentages will fluctuate based on jenkins performance.

Resolves https://github.com/ipfs/js-ipfs/issues/1666

### CODE REVIEW

**Comment by diasdavid** [comment]
@jacobheun can you get CI to become green?

**Comment by alanshaw** [comment]
@jacobheun did you check that there is an equivalent CLI / http-inject test for each http-daemon test that has been removed?

**Comment by jacobheun** [comment]
@alanshaw no, I haven't done that full comparison yet, I'll do a run through.

There are inject tests that need to get added as there are endpoints not being tested in either. There's no reason we shouldn't have 100% coverage on the api endpoints.  I think it would be good to couple that work with testing updates mentioned at https://github.com/ipfs/js-ipfs/issues/1666#issuecomment-433993559

**Comment by jacobheun** [comment]
I am going to close this for now, I think more discussion needs to occur on #1666 and that should become a larger testing discussion. We can open this later if it makes sense to proceed.

Looking through the tests I realized I removed the `interface` (interface-ipfs-core), which is removing a large suite of daemon tests. While this is highly redundant a significant audit needs to happen to make sure we're optimizing the tests appropriately. More thorough, mocked, http inject tests should be added before we remove the interface tests.

**Pull request closed without merging**
