### PR TITLE
fix: progress bar flakiness

### LINKED ISSUE #1041: progress bar disappears too soon
ref: https://github.com/ipfs/js-ipfs/pull/1036#issuecomment-337857265

### PR DESCRIPTION
**Pull request by dryajov**
this resolves #1041

### CODE REVIEW

**Comment by dryajov** [comment]
We still need to address the sec vulnerability here.

**Comment by dryajov** [comment]
@diasdavid This is going to be blocked until https://github.com/substack/static-module/pull/35 (or similar) is merged, we then need to propagate those changes over the dependency tree.

**Comment by diasdavid** [comment]
@dryajov this PR is not the one introducing that dependency, what do you mean by blocked?

**Comment by dryajov** [comment]
blocking in the sense that we probably shouldn't release js-ipfs without this fixed. But your right, we should not hold this PR because of it.

**Comment by attritionorg** [comment]
Without giving away too many details, can someone cliff notes the vulnerability / severity?

**Comment by dryajov** [comment]
@attritionorg here you go - https://nodesecurity.io/orgs/ipfs/projects/f983c9d5-424b-436a-ae6f-733dddb9ad08/1042. Keep in mind, this is a vulnerability in the `static-eval` that is used by many of our dependencies.

**Comment by attritionorg** [comment]
@dryajov Excellent, thank you!

**Pull request merged**
