### PR TITLE
Migrate to using undici instead of node-fetch

### PR DESCRIPTION
**Pull request by FlattestWhite**
Addresses: https://github.com/ipfs/js-ipfs/issues/4243

### CODE REVIEW

**Comment by BigLep** [comment]
@FlattestWhite : just curious why you closed this.

**Comment by FlattestWhite** [comment]
> @FlattestWhite : just curious why you closed this.

Ah I think I was running into some issues with some of the tests, got busy and then figured since I wasn't able to come back to this for a while, I closed it. I can open it back up and try and figure out the testing problem - if you think it's worth it

**Comment by BigLep** [comment]
Hi @FlattestWhite .  No pressure to open it, I was more just curious what caused you to abandon it.  I can't accurately to the priority.  Maintainer energy is starting to shift to https://github.com/ipfs/helia, and I don't know how relevant this work is for that effort.

**Comment by FlattestWhite** [comment]
> Hi @FlattestWhite . No pressure to open it, I was more just curious what caused you to abandon it. I can't accurately to the priority. Maintainer energy is starting to shift to https://github.com/ipfs/helia, and I don't know how relevant this work is for that effort.

Ahhh thanks for letting me know. Yeah I don't think this PR is worth keeping open then. It doesn't move the needle, and it was more for my open purpose of exploring the code base while contributing something.

**Pull request closed without merging**
