### PR TITLE
chore: add renovate

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR adds renovate service config.

Renovate works like greenkeeper but has filters. We have been talking about having a dependencies checker service to automatically do PRs with new versions but only for our packages. 

The config in the PR only enables packages matching `^ipfs` for now so we can test if this works well for us. 

Check this https://github.com/hugomrdias/js-ipfs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc to see what the PRs look like.

for this to work we need this service https://github.com/marketplace/renovate active for this repo. /cc @daviddias

### CODE REVIEW

**Comment by alanshaw** [comment]
Currently tests are always failing due to half complete circle config - we need to sort that out before we enable this.

**Comment by hugomrdias** [comment]
Ok I'll try to fix the config, do you feel it's useful to also activate gitlab CI but with the pre release and release in manual mode?

**Comment by alanshaw** [comment]
@hugomrdias yes lets do it ;)

**Comment by alanshaw** [comment]
I'm going to close this - we've enabled greenkeeper and it seems to be working quite well (now that we have stable CI). Will revisit if it becomes problematic.

**Pull request closed without merging**
