### PR TITLE
fix: limit SW registration to content root

### PR DESCRIPTION
**Pull request by lidel**
This PR introduces hardening proposed in https://github.com/ipfs/go-ipfs/issues/4025#issuecomment-342250616

go-ipfs version: https://github.com/ipfs/go-ipfs/pull/6801

### CODE REVIEW

**Comment by alanshaw** [comment]
@lidel any chance you can look into why linting is failing?

**Comment by lidel** [comment]
@alanshaw @hugomrdias `aegir` was missing from `PATH`, not sure why: 
master build works fine, same with other branch builds from yesterday. 
Clearing caches did not help, perhaps a Travis issue?

Anyway, switched calling linting via `npx aegir lint` in `.travis.yml` (https://github.com/ipfs/js-ipfs/pull/2682/commits/97dceb7ce74108c9d8d6d600bbbb94f51e3a32dd) and its now green.

**Comment by lidel** [comment]
CI fails due to unrelated test ("add recursively")

**Comment by alanshaw** [comment]
Yes, it looks like something changed in `it-glob` and it's not globbing empty directories...

@achingbrain any ideas?

**Comment by lidel** [comment]
(rebased on latest master)

**Comment by lidel** [comment]
@hugomrdias CI failed because `js-ipfsd-ctl#feat/force-kill` branch disappeared. I switched to ipfsd-ctl v2.1.0 but CI now fails with:

```
     Error: Cannot find module 'go-ipfs-dep/go-ipfs/ipfs'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      at resolveFileName (node_modules/resolve-from/index.js:29:39)
      at resolveFrom (node_modules/resolve-from/index.js:43:9)
      at module.exports (node_modules/resolve-from/index.js:46:47)
      at module.exports.moduleId (node_modules/ipfsd-ctl/node_modules/resolve-cwd/index.js:4:30)
```

(https://travis-ci.com/ipfs/js-ipfs/jobs/282596829#L1085)

Is there a fix or should we park this PR until `master` is green again?

**Comment by alanshaw** [comment]
When https://github.com/ipfs/js-ipfs/pull/2729 is merged (hopefully _really_ soon) you should be able to pick this up again. We _really_ should get this in 0.41.

**Comment by alanshaw** [comment]
@lidel I've rebased this

**Pull request merged**
