### PR TITLE
fix: upgrade aegir and ensure glob is mocked

### LINKED ISSUE #354: "Uncaught ReferenceError: window.Ipfs is not defined"
Using latest version `0.14.1`, I get an error:
"Uncaught ReferenceError: window.Ipfs is not defined"

This used to work at least in `0.13.0`.

If the global instance of IPFS has changed its name/location, it should be documented in the README.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Fixes #354, #353 and #336

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Tests are failing on node 6.3.0, all good on 6.2.2.

**Comment by dignifiedquire** [comment]
The issue is https://github.com/mafintosh/duplexify/issues/6

**Comment by dignifiedquire** [comment]
Fix is in https://github.com/mafintosh/duplexify/pull/7

**Comment by diasdavid** [comment]
Going ahead and merging this one. Opened a issue to fix Node.js 6.3.3 https://github.com/ipfs/js-ipfs/issues/373

Thank you @dignifiedquire :)

**Pull request merged**
