### PR TITLE
.add/files.add http-api endpoint

### PR DESCRIPTION
**Pull request by nginnever**
This continues <a href="https://github.com/ipfs/js-ipfs/pull/256">PR</a>

Currently the ```files add``` http resource is failing when the js-ipfs daemon is running do to this line in js-ipfs-api.

https://github.com/ipfs/js-ipfs-api/blob/master/src/get-dagnode.js#L30

@noffle might have some ideas on this. It seems that the js-ipfs-api ```object/data``` responses don't match when coming from js-ipfs and go-ipfs daemons.

### CODE REVIEW

**Comment by noffle** [comment]
Do you have some failing tests? (Travis only seems to be complaining about standard)  How can I repro?

**Comment by nginnever** [comment]
@noffle thanks for taking a look!

I'm going to add the cli tests with daemon on that should throw an error. I have just been manually trying to add a file with the go/js-ipfs daemons running.

**Comment by noffle** [comment]
Hey @nginnever, I noticed a couple of things:

1. It looks like js-ipfs is returning a Buffer for HTTP `object/data` and go-ipfs returns a stream. We really ought to update js-ipfs **and** [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core/#javascript---ipfsobjectdatamultihash-options-callback) to use streams consistently.
2. ipfs.files.add [returns `{ path: '...', node: DAGNode }`](https://github.com/ipfs/interface-ipfs-core/#javascript---ipfsfilesadddata-callback), not `{ Name: '...', Hash: '...' }`

**Comment by nginnever** [comment]
>1. It looks like js-ipfs is returning a Buffer for HTTP `object/data` and go-ipfs returns a stream. We really ought to update js-ipfs **and** [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core/#javascript---ipfsobjectdatamultihash-options-callback) to use streams consistently.

My thoughts exactly on the inconsistency in ```object```.  I will take a look at those commands and see about returning streams instead of the buffer (which i noticed that buffer isn't even the same data buffer that gets returned from the dag service so not sure what's going on there.)

>2

Ahh good catch, still some old tests slipping in before the changes to return type.

**Comment by nginnever** [comment]
@noffle I've created a branch on <a href="https://github.com/ipfs/js-ipfs-api/commit/0a154b64434a2eebaf5ddd7c2accc366131b03c2">js-ipfs-api</a> that updates ```get-dagNode.js``` to check the response from the daemons for buffer or stream.

Though the issue is still as mentioned above that sometimes the response from ```object/data``` is outputting a slightly different buffer causing the dag node to multihash to the incorrect value. 

If you run the tests now you will see this issue throw an error. Any thoughts on how the data buffers are getting changed when js-ipfs-api ```get-dagnode.js``` calls js-ipfs core ```object/data```? 

Seems like the core gets the proper data from the dagservice <a href="https://github.com/ipfs/js-ipfs/blob/master/src/core/ipfs/object.js#L159">here</a>. 

 but not when returned <a href="https://github.com/ipfs/js-ipfs-api/blob/master/src/get-dagnode.js#L28">here</a>.

**Comment by diasdavid** [comment]
@nginnever how is PR coming along?

**Comment by diasdavid** [comment]
Once https://github.com/ipfs/js-ipfs/pull/420 is merged, could you rebase this PR @nginnever ?

**Comment by diasdavid** [comment]
beep boop, https://github.com/ipfs/js-ipfs/pull/420 is merged :)

**Comment by diasdavid** [comment]
beep boop, needing this one for https://github.com/ipfs/js-ipfs/pull/432 :)

**Comment by VictorBjelkholm** [comment]
Needs https://github.com/ipfs/interface-ipfs-core/pull/71

**Comment by diasdavid** [comment]
@VictorBjelkholm got https://github.com/ipfs/js-ipfs/pull/323#issuecomment-245959028 released

**Comment by dignifiedquire** [comment]
Upgrade and merge conflict resolution happening here: #469

**Comment by diasdavid** [comment]
Ok, so @VictorBjelkholm finished up the integration and got all tests passing for get, cat and add 👏👏👏👏. Thank you @nginnever and @noffle for having kicked off all of this work 🌟 👌🏽

Now it is all about the big rebase (because js-ipfs codebase changed with the migration to pull-streams). This is happening here: https://github.com/ipfs/js-ipfs/pull/469 by @dignifiedquire 

Closing this PR, let's track the rest on the rebase PR (which is already pointing to master) https://github.com/ipfs/js-ipfs/pull/469

**Pull request closed without merging**
