### PR TITLE
fix: correct dht reference in ipns routing

### PR DESCRIPTION
**Pull request by kumavis**
interface was updated here https://github.com/libp2p/js-libp2p/pull/480

### CODE REVIEW

**Comment by kumavis** [comment]
I'm aware that this is intended to be changed to use the content-routing interface instead (https://github.com/ipfs/js-ipfs/issues/2921#issuecomment-617636762), but wanted to fix this bug (pushing in an undefined datastore) first as a quick fix

**Comment by kumavis** [comment]
seeing an error related to the dht, maybe theres a version mismatch to what you get in this repo (via lockfile) vs consuming this package elsewhere
```
ipfs:       AssertionError: expected undefined to deeply equal [Function: functionStub]
ipfs:       + expected - actual
ipfs:       -[undefined]
ipfs:       +[Function]
```

**Comment by kumavis** [comment]
not sure why codecov is failing

**Comment by kumavis** [comment]
strange
```
ipfs:       AssertionError: expected 'QmckaNuhfHhZe1wtQC9yPWtZXmu2g5svFnvSenzVu9dANf' to equal 'Qme79tX2bViL26vNjPsF3DP1R9rMKMvnPYJiKTTKPrXJjq'
ipfs:       + expected - actual
ipfs:       -QmckaNuhfHhZe1wtQC9yPWtZXmu2g5svFnvSenzVu9dANf
ipfs:       +Qme79tX2bViL26vNjPsF3DP1R9rMKMvnPYJiKTTKPrXJjq
ipfs:       
ipfs:       at Context.it (/home/travis/build/ipfs/js-ipfs/packages/interface-ipfs-core/src/add.js:5:437)
ipfs:       at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by achingbrain** [comment]
Looks good for the most part, not sure about the CI failure, it seems unrelated.

Is there a test that could have picked this up?

**Comment by kumavis** [comment]
test failure also seems to fail on node v10 and not on v12

**Comment by kumavis** [comment]
when i run the tests locally on master on node v10 i get lots of failures
a lot of them are associated with an "invalid block" error associated with 
`ipfs-repo`'s `.add` `Block.isBlock(block)` guard.

the block passed in resembles a block but doesn't pass the `ipfs-block`'s `Block.isBlock(block)`'s `(obj) => !!(obj && obj[symbol])` implementation

**Comment by kumavis** [comment]
@achingbrain @vasco-santos  test failures same as on master https://github.com/ipfs/js-ipfs/pull/3000

**Comment by achingbrain** [comment]
The `should add a BIG buffer` test is failing on Node 10 due to an upgrade to `ipld-dag-pb`, the fix is here: https://github.com/ipld/js-ipld-dag-pb/pull/179

**Pull request merged**
