### PR TITLE
Feat/benchmarks

### PR DESCRIPTION
**Pull request by diasdavid**
@pgte just found this stale branch. Could you share a description of this work and next steps?

### CODE REVIEW

**Comment by diasdavid** [comment]
@pgte ?

**Comment by diasdavid** [comment]
@pgte ping

**Comment by diasdavid** [comment]
@pgte closing given lack of response

**Comment by pgte** [comment]
@diasdavid sorry about this, but I've been putting this off because it was done some time ago and I had to take the time to reload all the context.
Anyway, I have some pending related work to do related to this, which is trying to speed up the DAG nodes retrieval for the case of CRDTs: https://github.com/ipfs/dynamic-data-and-capabilities/issues/3

This will perhaps require me to revisit this, since I want to measure it, and have a base line I can try to improve on.

**Comment by diasdavid** [comment]
Ack :) restored the branch for you then :)

**Pull request closed without merging**
