### PR TITLE
feat: Add support for dag-jose

### PR DESCRIPTION
**Pull request by oed**
Support for dag-jose was recently merged into go-ipfs https://github.com/ipfs/go-ipfs/pull/8569. This PR adds support for dag-jose in the `js-ipfs-http-client` so that the new codec in go-ipfs can be used from javascript environments.

A few notes:
- This is not super urgent as it's easy to plug in additional ipld codecs in javascript. More of a nice to have to be symmetric with go-ipfs
- Maybe the `ipfs-core` package should also support dag-jose?

### CODE REVIEW

**Comment by achingbrain** [comment]
> it's easy to plug in additional ipld codecs in javascript

This is very much intentional - there's no need to add extra codecs here which increase the bundle size, install times, etc.

The idea is that if you need a special codec or there's a new release of one or whatever you can configure it yourself without needing to PR this project or wait for a release.

**Comment by achingbrain** [comment]
..I say that, but of course `go-ipfs` is shipping with support for `dag-jose` by default so `js-ipfs` will need to do the same thing.

To merge this PR it needs:

1. support for `dag-jose` added to `ipfs-core` - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-core/src/components/index.js#L290
2. The version of go-ipfs used in tests upgraded to one that has `dag-jose` support - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/package.json#L87
3. tests added to the `ipfs.dag.get`/`ipfs.dag.put` suites in `interface-ipfs-core` that exercise the `dag-jose` support - https://github.com/ipfs/js-ipfs/tree/master/packages/interface-ipfs-core/src/dag
	- see the npm scripts for running interface tests - https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/package.json#L63-L66

**Comment by oed** [comment]
Thanks @achingbrain will prioritize this!

**Comment by oed** [comment]
Replaced by #3989, closing.

**Pull request closed without merging**
