### PR TITLE
[WIP] feat: ready promise

### PR DESCRIPTION
**Pull request by pkafei**
Related to https://github.com/ipfs/js-ipfs/issues/1762

### CODE REVIEW

**Comment by mikeal** [comment]
RE: documentation. Do we want to update the README to move all the examples to use this?

**Comment by alanshaw** [comment]
> RE: documentation. Do we want to update the README to move all the examples to use this?

Yes, this should be the recommended way of obtaining a ready node.

Separately, I think we should stop advertising the callback API (both in the README and the examples) so predominantly. Instead just document that all the API methods support callbacks. I want new users to be using promises so that when https://github.com/ipfs/js-ipfs/issues/1670 lands it's easier for them to upgrade.

re: the [examples here](https://github.com/ipfs/js-ipfs/tree/master/examples) I think we should submit a separate PR to switch them _all_ to using async await style, I'd rather not mix `await ipfs.ready` with callbacks.

**Comment by alanshaw** [comment]
@pkafei ping

**Comment by pkafei** [comment]
> @pkafei ping

@alanshaw Saw comment and will give detailed response shortly.

**Comment by pkafei** [comment]
> Yes, this should be the recommended way of obtaining a ready node.
> 
> Separately, I think we should stop advertising the callback API (both in the README and the examples) so predominantly. Instead just document that all the API methods support callbacks. I want new users to be using promises so that when #1670 lands it's easier for them to upgrade.
> 
> re: the examples here I think we should submit a separate PR to switch them all to using async await style, I'd rather not mix await ipfs.ready with callbacks.

Just want to reiterate the scope of this ticket. Here I'm implementing ready promise, and I'll update the README (docs) and add a test. 

@mikeal and I plan on updating all the callbacks in the `js-ipfs` codebase to use async await in future tickets. I think it would be better for us to update all of the examples _after_ we have refactored all of the callbacks to async await. Alternatively we can update the examples as we go.

**Comment by alanshaw** [comment]
@pkafei do you need some help getting this finished?

**Comment by pkafei** [comment]
@alanshaw Yes, I need help writing the test.

**Pull request closed without merging**
