### PR TITLE
feat: replace websocket-star with stardust

### PR DESCRIPTION
**Pull request by mkg20001**
`<humor>`

feat: websocket-star? what's that. only heard of stardust!

(...psst, we're replacing ws-star with stardust, which does
the same things, except it's way faster & more secure)

`</humor>`

### CODE REVIEW

**Comment by mkg20001** [comment]
I've replaced all occurrences of ws-star with stardust
I'd have to add the necessary code to enable stardust as well, after that it should be ready

**Comment by mkg20001** [comment]
Ref https://github.com/libp2p/js-libp2p-websocket-star/issues/70#issuecomment-548339100

**Comment by mkg20001** [comment]
Currently working on the custom bundle replacement

**Comment by mkg20001** [comment]
Need a feature: https://github.com/ipfs/js-ipfs/issues/2579

**Comment by mkg20001** [comment]
Also would need some feedback on my idea with the `overrideFunction` option

**Comment by mkg20001** [comment]
Test failure seems to be
```
  1) cli
       name-pubsub
         enabled
           pubsub commands
             should subscribe on name resolve:
     AssertionError: expected '/ipns/6PMMeVwh7iFvzYhDNDrYGu3cZkodekveUtTK7vJd7bcVZ\n' to contain '/ipns/Qmer8WkQ4d6uJztVafjf3AiXyaLpmesnS678yYGnQ7mf34'
      at Context.<anonymous> (test/cli/name-pubsub.js:92:30)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

seems unreleated

**Comment by mkg20001** [comment]
We could rename `overrideFunction` to `hooks` and make it an array, to allow adding multiple modules at once (`stardust4ipfs` + `webrtc4ipfs` for ex)

**Comment by alanshaw** [comment]
@mkg20001 can you please base this PR on https://github.com/ipfs/js-ipfs/pull/2591? It should allow you to add stardust easily without adding more configuration options and complexity.

**Comment by alanshaw** [comment]
ping @mkg20001

**Comment by alanshaw** [comment]
ping @mkg20001 - do you want me to pull this one over the line?

**Comment by mkg20001** [comment]
Yes

**Comment by mkg20001** [comment]
https://github.com/ipfs/js-ipfs/pull/2600

**Comment by mkg20001** [comment]
@alanshaw Oh wait I understood "Do you want to pull this over the line?" :sweat_smile:

**Comment by lidel** [comment]
@mkg20001  just to be sure I got this right: 
this PR should be closed, and @alanshaw should review https://github.com/ipfs/js-ipfs/pull/2600, is that correct?

**Comment by mkg20001** [comment]
Correct

**Pull request closed without merging**
