### PR TITLE
feat: allow controlling preload behaviour from cli

### PR DESCRIPTION
**Pull request by achingbrain**
Pulled out from #2379

Depends on:

* [x] https://github.com/ipfs/js-ipfs/pull/2391

### CODE REVIEW

**Comment by alanshaw** [comment]
Should this be exposed in the HTTP API? Otherwise this won't work when talking to a daemon. Also, should `ipfs daemon --enable-preload=false` take precedence?

**Comment by achingbrain** [comment]
> Should this be exposed in the HTTP API?

Good point, I have added this.

> Should `ipfs daemon --enable-preload=false` take precedence?

Not sure. I guess maybe if you've specified it explicitly?

**Comment by achingbrain** [comment]
Exposed in `ipfs-http-client` here: https://github.com/ipfs/js-ipfs-http-client/pull/1079

**Comment by alanshaw** [comment]
> > Should `ipfs daemon --enable-preload=false` take precedence?
> 
> Not sure. I guess maybe if you've specified it explicitly?

Just looked in the preload component and this happens already. If you start the daemon with `--enable-preload=false` then specifying `preload: true` here will have no effect.

**Pull request merged**
