### PR TITLE
Migration of Blockstore to use multihash instead of CID as key

### PR DESCRIPTION
**Pull request by AuHau**
Related to https://github.com/ipfs/js-ipfs/issues/2415

Since DHT is not enabled, I have not worked on that part.

#### TODO

 - [ ] Bump `js-ipfs-repo` version upon release
 - [ ] Bump `interface-js-ipfs-core` version upon release
 - [ ] Change DHT to use multihashes instead CIDs 
 - [ ] Fix GC tests that I think never properly worked, but I have idea about what is wrong, seems like `ipfs.block.rm()` actually does not delete the blocks...

#### Blocked by

 - [x] https://github.com/ipfs/js-ipfs-repo-migrations/pull/1
 - [ ] https://github.com/ipfs/js-ipfs-repo-migrations/pull/4
 - [ ] https://github.com/ipfs/interface-js-ipfs-core/pull/540
 - [ ] https://github.com/ipfs/js-ipfs-repo/pull/211
 - [ ] https://github.com/ipfs/js-ipfs-http-client/pull/1128

### CODE REVIEW

**Comment by daviddias** [comment]
@AuHau can this endeavor has so many tails that I'm having a hard time understanding what needs to happen first. Can you elaborate on what PRs need to be reviewed/merged/released first so that we can land things sequentially?

**Comment by AuHau** [comment]
Hahah yeah, it is getting pretty tangled 😅

Well there are few parts:

 1. `js-ipfs-repo-migrations` tool to be finalized and released first version
     - https://github.com/ipfs/js-ipfs-repo-migrations/pull/1 - the general first version of the tool PR
     - https://github.com/ipfs/js-ipfs-repo-migrations/pull/2 - migration for this and https://github.com/ipfs/js-ipfs/issues/1937 (although not so sure if it is needed anymore)
 2. `js-ipfs-repo-migrations` tool to be integrated
     - https://github.com/ipfs/js-ipfs-repo/pull/202
     - https://github.com/ipfs/js-ipfs/pull/2044 - I will have to work on this one as the async/await `ipfs-repo` is now integrated so it is unblocked...
 3. merge related changes
     - encoded key's names: https://github.com/ipfs/js-ipfs/pull/2410
     - multihash block key: 
          - https://github.com/ipfs/interface-js-ipfs-core/pull/540
 		  - https://github.com/ipfs/js-ipfs-repo/pull/211
          - and this PR

Steps 2. and 3. will have to happen pretty much in the same time...

**Comment by daviddias** [comment]
Hi! js-ipfs master just got a whole new set of automated tests with #2528, https://github.com/ipfs/js-ipfs/pull/2440 and also running some of the test suites from our early testers (hi5 to  @achingbrain for setting it all up!). **Would you mind rebasing the master branch on this PR to ensure it runs all the latest tests? Thank you!**

**Comment by achingbrain** [comment]
Closing in favour of #3124

**Pull request closed without merging**
