### PR TITLE
feat: merge of get and resolve

### PR DESCRIPTION
**Pull request by diasdavid**
needs https://github.com/ipfs/interface-ipfs-core/pull/116

### CODE REVIEW

**Comment by diasdavid** [comment]
@dignifiedquire 

```
 1) bitswap connections fetches a remote block 2 peers:
     Error: Uncaught Error: Please use a browser with webcrypto support (webpack:///~/multihashing-async/src/crypto-sha1-2-browser.js:21:0 <- test/core/bitswap.spec.js:93350)

  

  2) bitswap connections fetches a remote block 3 peers:
     Error: Please use a browser with webcrypto support
    at webCryptoHash (webpack:///~/multihashing-async/src/crypto-sha1-2-browser.js:21:0 <- test/core/bitswap.spec.js:93350:11)
    at sha2256 (webpack:///~/multihashing-async/src/crypto-sha1-2-browser.js:49:0 <- test/core/bitswap.spec.js:93378:3)
    at Function.Multihashing.digest (webpack:///~/multihashing-async/src/index.js:60:0 <- test/core/bitswap.spec.js:31842:3)
    at Multihashing (webpack:///~/multihashing-async/src/index.js:18:0 <- test/core/bitswap.spec.js:31800:16)
    at Block.key (webpack:///~/ipfs-block/src/index.js:55:0 <- test/core/bitswap.spec.js:15480:5)
    at map (webpack:///test/core/bitswap.spec.js:165:0 <- test/core/bitswap.spec.js:162601:38)
    at webpack:///~/async/internal/map.js:22:0 <- test/core/bitswap.spec.js:40996:9
    at eachOfArrayLike (webpack:///~/async/eachOf.js:57:0 <- test/core/bitswap.spec.js:11798:9)
    at exports.default (webpack:///~/async/eachOf.js:9:0 <- test/core/bitswap.spec.js:11750:5)
    at _asyncMap (webpack:///~/async/internal/map.js:20:0 <- test/core/bitswap.spec.js:40994:5)

  

  3) bitswap connections fetches a remote file 2 peers:
     Error: Uncaught Error: Please use a browser with webcrypto support (webpack:///~/multihashing-async/src/crypto-sha1-2-browser.js:21:0 <- test/core/bitswap.spec.js:93350)
```

**Comment by dignifiedquire** [comment]
Sounds like some dependencies have not yet bubbled up yet. I suggest staying with aegir 9 until we have ensured all deps are updated and released.

**Comment by diasdavid** [comment]
I'll just update everything right now as part of https://github.com/ipfs/community/issues/225#issuecomment-278667534

**Comment by diasdavid** [comment]
> https://github.com/ipfs/js-ipfs/pull/761#issuecomment-278668549

done, phew, this took a bit.

**Comment by diasdavid** [comment]
And CI is now green :D

**Pull request merged**
