### PR TITLE
feat: use pull-mplex

### PR DESCRIPTION
**Pull request by jacobheun**
- [x] run ipfs/interop tests against this change

### CODE REVIEW

**Comment by hugomrdias** [comment]
any chance i can help out with this ? this PR fixes vue support and protoschool

**Comment by jacobheun** [comment]
@hugomrdias i just rebased this with master so it has the latest updates. I have a WIP pr over at https://github.com/ipfs/interop/pull/59 that I haven't been able to spend a ton of time on. I think this is in a good spot, but the interop tests have been unreliable as of late. It would be nice to get more deterministic results there.

**Comment by alanshaw** [comment]
@jacobheun can we ship this? 🚢 😁 🙏

**Comment by jacobheun** [comment]
@alanshaw not yet, ipfs/interop has an issue with pubsub I did not have a chance to look at last week. I will look into it more today/tomorrow.

**Comment by jacobheun** [comment]
The underlying issue with pubsub interop has been fixed, this is ready to go. You can see the passing interop tests at https://github.com/ipfs/interop/pull/67.

**Pull request merged**
