### PR TITLE
Implement "file ls"

### PR DESCRIPTION
**Pull request by richardschneider**
Add `file ls` to both the CLI and HTTP API.  CLI [docs](https://ipfs.io/docs/commands/#ipfs-file-ls) and API [docs](https://ipfs.io/docs/api/#api-v0-file-ls).

### CODE REVIEW

**Comment by diasdavid** [comment]
@richardschneider I had understood from IRC that you opted by the direction of not using file ls anymore, did that change?

**Comment by richardschneider** [comment]
It turns out there is just not enough information about the directory.  Also, asking for file information is not supported (I think)

> http://localhost:5001/api/v0/file/ls?arg=/ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test
```
{
    "Arguments": {
        "/ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test": "QmNtpA5TBNqHrKf3cLQ1AiUKXiE4JmUodbG5gXrajg8wdv"
    },
    "Objects": {
        "QmNtpA5TBNqHrKf3cLQ1AiUKXiE4JmUodbG5gXrajg8wdv": {
            "Hash": "QmNtpA5TBNqHrKf3cLQ1AiUKXiE4JmUodbG5gXrajg8wdv",
            "Size": 277,
            "Type": "Directory",
            "Name": "test",
            "Links": [
                {
                    "Hash": "QmTz3oc4gdpRMKP2sdGUPZTAGRngqjsi99BPoztyP53JMM",
                    "Size": 12,
                    "Type": "File",
                    "Name": "bar"
                },
                {
                    "Hash": "QmX1ebVUtfY11ZCpVmqyE5mDoN62SpLd8eLPpg5GGV1ABt",
                    "Size": 114,
                    "Type": "Directory",
                    "Name": "baz"
                },
                {
                    "Hash": "QmYNmQKp6SuaVrpgWRsPTgCQCnpxUYGq76YEKBXuj2N4H6",
                    "Size": 12,
                    "Type": "File",
                    "Name": "foo"
                }
            ]
        }
    }
}
```

> http://localhost:5001/api/v0/ls?arg=/ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test

```
{
    "Objects": [
        {
            "Hash": "/ipfs/QmRCJXG7HSmprrYwDrK1GctXHgbV7EYpVcJPQPwevoQuqF/test",
            "Links": [
                {
                    "Name": "test",
                    "Hash": "QmNtpA5TBNqHrKf3cLQ1AiUKXiE4JmUodbG5gXrajg8wdv",
                    "Size": 277,
                    "Type": 1
                }
            ]
        }
    ]
}
```

**Comment by richardschneider** [comment]
I've raised https://github.com/ipfs/js-ipfs/issues/1079, about the subfolder issue.  However, to summarise why I can't use `ipfs ls`

- Doesn't provide information about the specified directory, only is contents
- Doesn't accept a file.  We use for `fstat` information

So instead of breaking interfaces, I just implemented an existing interface.

PS: This got [mounting IPFS on windows]( https://github.com/richardschneider/net-ipfs-mount) with js-ipfs working 🕺

**Comment by richardschneider** [comment]
@diasdavid LGTM

**Pull request merged**
