### PR TITLE
Add additional preloaders

### PR DESCRIPTION
**Pull request by coryschwartz**
Adding more preloaders, see the following issue.
https://github.com/protocol/bifrost-infra/issues/233

### CODE REVIEW

**Comment by alanshaw** [comment]
I'm not clear from the issue, are these up and running @coryschwartz or still in the process of being setup?

**Comment by coryschwartz** [comment]
Still in the process, but I think they will be up and running by today.

**Comment by alanshaw** [comment]
Nice, these also need to be added to the bootstrap lists here:

* https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-nodejs.js
* https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/config-browser.js

**Comment by achingbrain** [comment]
These were added in a different PR

**Pull request closed without merging**
