### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
@dignifiedquire now that duplexify is solved, seems it fails on the CLI stuff

**Comment by dignifiedquire** [comment]
I'm merging this, as it is a strict improvement over what is currently in `master`

**Comment by diasdavid** [comment]
@dignifiedquire don't merge things without CI unless that there is a very strong reason to.

**Comment by dignifiedquire** [comment]
@diasdavid there is, current `master` is already red and I'm trying to get it green, of which this PR is part of

**Pull request merged**
