### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
A normal `jsipfs init` is now failing making all CLI tests fail. Investigating

```
» jsipfs init
initializing ipfs node at /Users/imp/.jsipfs
generating 2048-bit RSA keypair...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: repo is not initialized yet
    at parallel (/Users/imp/code/js-ipfs/node_modules/ipfs-repo/src/index.js:216:41)
    at /Users/imp/code/js-ipfs/node_modules/async/internal/parallel.js:39:9
    at /Users/imp/code/js-ipfs/node_modules/async/internal/once.js:12:16
    at iterateeCallback (/Users/imp/code/js-ipfs/node_modules/async/internal/eachOfLimit.js:44:17)
    at /Users/imp/code/js-ipfs/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/imp/code/js-ipfs/node_modules/async/internal/parallel.js:36:13
    at get (/Users/imp/code/js-ipfs/node_modules/ipfs-repo/src/version.js:53:18)
    at ReadFileContext.store.get (/Users/imp/code/js-ipfs/node_modules/ipfs-repo/src/version.js:29:18)
    at ReadFileContext.callback (/Users/imp/code/js-ipfs/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

```

**Comment by diasdavid** [comment]
The issue I was having was introduced with https://github.com/ipfs/js-ipfs-repo/commit/755b5c60436d1ccb58be71fc18b637b51542a107, reverted ipfs-repo to 0.20.0. 

@hugomrdias can you triple check what caused the issue? Seems that the merge of two error states on ipfs-repo, `if err` and res.config is not being handled correctly.

**Comment by diasdavid** [comment]
Only one flaky test made the CI fail :(

```
 1) interface-ipfs-core tests,.files

       "after all" hook:

     AssertionError: The libp2p node is not started yet

    at Node.dialProtocol (webpack:///node_modules/libp2p/src/index.js:248:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:277981:5)

    at libp2p.dialProtocol (webpack:///node_modules/ipfs-bitswap/src/network.js:169:0 <- node_modules/aegir/src/config/karma-webpack-bundle.js:256030:21)
```

Going to go ahead and merge this one so that other PRs can rebased on master. Soon there will be no more flaky tests!

**Comment by VictorBjelkholm** [comment]
> Only one flaky test made the CI fail :(
@diasdavid in the future we see flaky tests, let's add `this.retries(3)` to them + a comment, so we can make them less flaky.

**Comment by diasdavid** [comment]
@VictorBjelkholm 👍. Waiting to have #1336 merged :)

**Pull request merged**
