### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by alanshaw**

### CODE REVIEW

**Comment by olizilla** [comment]
@alanshaw @diasdavid Getting this in would release the fix for the "already piped" errors, that you get when you leave a js-ipfs  node running for a while. https://github.com/libp2p/js-libp2p-switch/issues/235

There are 28 days of other libp2p updates behind that version increment, so we'd need to run all the third party app tests again to feel confident there are no surprises, but you know, ONLY FORWARDS!

cc @jacobheun

**Comment by diasdavid** [comment]
This one keeps appearing.

```
  1) ping DHT disabled "before all" hook:

     Error: Error: A node cannot dial itself

      at parseError (node_modules/ipfs-api/src/utils/send-request.js:17:17)

      at ClientRequest.<anonymous> (node_modules/ipfs-api/src/utils/send-request.js:47:14)

      at ClientRequest.EventEmitter.emit (domain.js:442:20)

      at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)

      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)

      at Socket.socketOnData (_http_client.js:432:20)

      at Socket.EventEmitter.emit (domain.js:442:20)

      at addChunk (_stream_readable.js:283:12)

      at readableAddChunk (_stream_readable.js:264:11)

      at Socket.Readable.push (_stream_readable.js:219:10)

      at TCP.onread (net.js:635:20)
```

**Comment by diasdavid** [comment]
Saw one failure but not related with tests. Jenkins is having a bad day today

image

**Comment by diasdavid** [comment]
Only test failing now is related with preload

```

  1) MFS preload should preload MFS root periodically:


      Uncaught AssertionError: expected [ 'QmSame' ] to deeply equal [ 'QmSame', 'QmUpdated' ]

      + expected - actual


       [

         "QmSame"

      +  "QmUpdated"

       ]

      

      at preloader.stop (test/core/mfs-preload.spec.js:48:21)

      at Object.stop (src/core/mfs-preload.js:48:7)

      at Timeout.setTimeout [as _onTimeout] (test/core/mfs-preload.spec.js:43:19)
```

**Comment by diasdavid** [comment]
Just missing stuff that is not related with this PR

image

**Pull request merged**
