### PR TITLE
Add basic example using ES7 async/await

### PR DESCRIPTION
**Pull request by enricomarino**

### CODE REVIEW

**Comment by diasdavid** [comment]
I feel that this one should be an external example since we don't support async/await natively.

**Comment by enricomarino** [comment]
you mean for the browser support?

**Comment by enricomarino** [comment]
(making the examples with promises) I noticed that `init` and `start` are not promisified in the lib,  could we promisify them in the lib?

**Comment by diasdavid** [comment]
@enricomarino good catch. Yeah, wanna PR that in?

**Comment by enricomarino** [comment]
sure!

**Comment by diasdavid** [comment]
Awesome! Closing this one PR then. Ping me when you make the PR to add promises to init and start, that should trickle an update of the previously added promises example. Thanks!

**Comment by enricomarino** [comment]
(Already made when posted, so...) ping!
Promisify init https://github.com/ipfs/js-ipfs/pull/866
Promisify start https://github.com/ipfs/js-ipfs/pull/867

(I thought you were automatically notified, 
but I imagine you've lots of notifications to check...)

**Comment by diasdavid** [comment]
Rad, thank you!

> (I thought you were automatically notified, but I imagine you've lots of notifications to check...)

it is a bit like that these days, yes :)

**Pull request closed without merging**
