### PR TITLE
bootstrap peers

### PR DESCRIPTION
**Pull request by heavyk**
playing around with the code, I couldn't get it transferring ... however, if I dial them, everything is working perfectly.

not sure if this is exactly how you wanted it implemented though. feedback appreciated

cheers

### CODE REVIEW

**Comment by diasdavid** [comment]
Hey @heavyk, thank you for the PR!

Bootstrap peers are one of the Discovery mechanisms of libp2p, currently implemented in https://github.com/libp2p/js-libp2p-railing, just not attached to the libp2p-builds. Would you like to do that?

Note that the go-ipfs nodes running on bootstrap have version 0.4.3, which doesn't incorporate some spdy fixes that are presente in go-ipfs master, when 0.4.4 is released, you shouldn't have an issue :) (Also one of the reasons we are not enabling this by default)

**Comment by heavyk** [comment]
oh alright, I didn't know about the differences in the versions. I'd be more than happy to implement it using libp2p-railing ... I pushed another commit which implements it how I expected it to go, but I get this error:

```
Swarm listening on /ip4/127.0.0.1/tcp/59152
/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19
      peers[peerInfo.id.toB58String()].multiaddr.replace([], peerInfo.multiaddrs);
                                                ^

TypeError: Cannot read property 'replace' of undefined
    at PeerBook.put (/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19:49)
    at Swarm.self._libp2pNode.swarm.on (/Users/kenny/Projects/js-ipfs/src/core/components/libp2p.js:32:35)
    at emitOne (events.js:101:20)
    at Swarm.emit (events.js:188:7)
    at /Users/kenny/Projects/js-ipfs/node_modules/libp2p-swarm/lib/dial.js:159:19
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/dialer.js:66:9
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/agreement.js:32:5
    at /Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:93:9
    at Object.cb (/Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:105:5)
    at drain (/Users/kenny/Projects/js-ipfs/node_modules/pull-reader/index.js:39:14)
```

is my implementation even correct to begin with?

---

also, I'll be more than happy to help with other parts that need to be done. just point me in the right direction :D

**Comment by diasdavid** [comment]
@heavyk you missed an 's' in the `.multiaddr` :)

**Comment by heavyk** [comment]
nope :) that doesn't work either... I instear get this error:

```
/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19
      peers[peerInfo.id.toB58String()].multiaddrs.replace([], peerInfo.multiaddrs);
                                                  ^

TypeError: peers[peerInfo.id.toB58String(...)].multiaddrs.replace is not a function
    at PeerBook.put (/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19:51)
    at Swarm.self._libp2pNode.swarm.on (/Users/kenny/Projects/js-ipfs/src/core/components/libp2p.js:32:35)
    at emitOne (events.js:101:20)
    at Swarm.emit (events.js:188:7)
    at /Users/kenny/Projects/js-ipfs/node_modules/libp2p-swarm/lib/dial.js:159:19
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/dialer.js:66:9
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/agreement.js:32:5
    at /Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:93:9
    at Object.cb (/Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:105:5)
    at drain (/Users/kenny/Projects/js-ipfs/node_modules/pull-reader/index.js:39:14)
```

I did get it working though... look at the last commit. I had to `put(peerInfo, true)` (to force replacement). however, that will yield this error:

```
/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19
      peers[peerInfo.id.toB58String()].multiaddr.replace([], peerInfo.multiaddrs);
                                                ^

TypeError: Cannot read property 'replace' of undefined
    at PeerBook.put (/Users/kenny/Projects/js-ipfs/node_modules/peer-book/lib/index.js:19:49)
    at /Users/kenny/Projects/js-ipfs/node_modules/libp2p-ipfs/lib/index.js:147:22
    at /Users/kenny/Projects/js-ipfs/node_modules/libp2p-swarm/lib/dial.js:192:11
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/dialer.js:66:9
    at /Users/kenny/Projects/js-ipfs/node_modules/multistream-select/lib/agreement.js:32:5
    at /Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:93:9
    at Object.cb (/Users/kenny/Projects/js-ipfs/node_modules/pull-length-prefixed/lib/decode.js:105:5)
    at drain (/Users/kenny/Projects/js-ipfs/node_modules/pull-reader/index.js:39:14)
    at more (/Users/kenny/Projects/js-ipfs/node_modules/pull-reader/index.js:51:13)
    at Object.reader.read (/Users/kenny/Projects/js-ipfs/node_modules/pull-reader/index.js:95:7)
➜  js-ipfs git:(bootstrap-peers) ✗ atom /Users/kenny/Projects/js-ipfs/node_modules/libp2p-ipfs/lib
```

so then, I had to go here: https://github.com/ipfs/js-libp2p-ipfs/blob/master/src/index.js#L145 and change that line to: `this.peerBook.put(peer, true)`

and now everything is all good. I'm not sure that's the right way though...

**Comment by heavyk** [comment]
I see what you're saying about the 's' though... that's an existing error in peer-book

**Comment by heavyk** [comment]
seems the peer-book code is incorrect. you were the last to touch that anyway: https://github.com/libp2p/js-peer-book/commit/e58fa0c98b32355f42874894245bac8817fadc50

how shall this be fixed then?

**Comment by diasdavid** [comment]
nvm, when I looked at first, I thought you wanted to access the array directly, the .replace exists: https://github.com/libp2p/js-peer-info/blob/master/src/index.js#L76

**Comment by heavyk** [comment]
really, I'm not sure what I'm not sure what exactly is the desired functionality... though, I can do the work if you tell me how it is you want it.

**Comment by diasdavid** [comment]
Thank you :) In order to make railing work, we need:

- [ ] Update https://github.com/libp2p/js-libp2p-railing
  - Update all the dependencies
  - Make sure tests pass
- [ ] Add railing to https://github.com/ipfs/js-libp2p-ipfs by adding a method to `this.bootstrap = (multiaddrs) => {...}`
  - Then, for each peer that gets emitted on https://github.com/libp2p/js-libp2p-railing/blob/master/src/index.js#L33, do the same as https://github.com/ipfs/js-libp2p-ipfs-browser/blob/master/src/index.js#L59-L61. This will make dials for the peers 'discovered' https://github.com/ipfs/js-ipfs/blob/master/src/core/components/libp2p.js#L19-L22

Let me know your questions as you go, and thanks for bearing with the lack of good docs. We have the intent of boosting all our documentation on these things in the next quarter, so that contributions and usage gets way easier.

**Comment by diasdavid** [comment]
Hi @heavyk, we've added bootstrap through libp2p-railing with this PR https://github.com/ipfs/js-ipfs/pull/735

Thank you for taking a look at this, we had to refactor to match our libp2p interfaces.

If you are looking for more things to work on, check other issues that are open for contribution here: https://waffle.io/ipfs/js-ipfs

**Pull request closed without merging**
