### PR TITLE
tests: add stats and update interface-ipfs-core

### PR DESCRIPTION
**Pull request by hacdias**

### CODE REVIEW

**Comment by hacdias** [comment]
@diasdavid the tests are failing here:

```
1) .stats
       .bitswap:
     TypeError: Cannot read property 'bitswap' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:35:18)

  2) .stats
       .bitswap Promise:
     TypeError: Cannot read property 'bitswap' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:52:25)

  3) .stats
       .bw:
     TypeError: Cannot read property 'bw' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:67:18)

  4) .stats
       .bw Promise:
     TypeError: Cannot read property 'bw' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:79:25)

  5) .stats
       .repo:
     TypeError: Cannot read property 'repo' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:89:18)

  6) .stats
       .repo Promise:
     TypeError: Cannot read property 'repo' of undefined
      at Context.it (node_modules\interface-ipfs-core\src\stats.js:102:25)
```

Is there any step on the tests I should've done? They seem to work with the API.

**Comment by hacdias** [comment]
@diasdavid just noticed JS-IPFS doesnt have .stats implemented.

**Comment by hacdias** [comment]
I'll add the bypass to the tests on interface-ipfs-core.

**Comment by hacdias** [comment]
Ref.: https://github.com/ipfs/interface-ipfs-core/pull/209

**Comment by diasdavid** [comment]
@hacdias wanna try to take a stab at implementing them?

**Comment by hacdias** [comment]
@diasdavid I'll open an issue and assign it to myself. In the meanwhile, I suggest to merge this 😄

**Comment by diasdavid** [comment]
@hacdias 👍 just waiting on the CI

**Comment by hacdias** [comment]
@diasdavid Travis seems to have passed 😄

**Pull request merged**
