### PR TITLE
Add blob-stores to deps instead of devDeps

### PR DESCRIPTION
**Pull request by VictorBjelkholm**
We depend on these in the application and they are needed to run

https://github.com/ipfs/js-ipfs/blob/1c64247ab92b6565f071657cdfbe0d22a5bcf9d9/src/core/default-repo/node.js#L4
https://github.com/ipfs/js-ipfs/blob/37db11e40ff83761afdfd6a4db33ffcd3f393be1/src/cli/commands/init.js#L5
https://github.com/ipfs/js-ipfs/blob/1c64247ab92b6565f071657cdfbe0d22a5bcf9d9/src/core/default-repo/browser.js#L3

### CODE REVIEW

**Comment by dignifiedquire** [comment]
thanks :) can you please change the commit message to follow our convention? sth like `fix(deps): move blob stores to dependencies`

**Comment by VictorBjelkholm** [comment]
@dignifiedquire ah, of course! Forgot... We should have a post-commit lint for that!

**Comment by VictorBjelkholm** [comment]
@dignifiedquire commit msg fixed!

**Comment by dignifiedquire** [comment]
lgtm

**Comment by dignifiedquire** [comment]
Sorry @VictorBjelkholm could you rebase onto `master` please, seems there is a merge conflict

**Comment by diasdavid** [comment]
@VictorBjelkholm can you add this -- https://github.com/ipfs/js-ipfs/pull/502#issuecomment-247784072 --  as a feature request for aegir?

**Comment by VictorBjelkholm** [comment]
@dignifiedquire rebased! \o/

@diasdavid Opened! https://github.com/dignifiedquire/aegir/issues/59

**Comment by diasdavid** [comment]
thank you @VictorBjelkholm :)

**Pull request merged**
